-- ═══════════════════════════════════════════════════════
-- Question bank import
-- Run in: Supabase → SQL Editor → New query → Run
--
-- Wrapped in a transaction: if any row fails, nothing is
-- inserted and the bank is left exactly as it was.
-- Running it twice inserts the questions twice, so run once.
-- ═══════════════════════════════════════════════════════

begin;

-- 06-anatomy-physiology-2.txt — 16 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 6 — Anatomy and Physiology, second set$x$, $x$Basic Sciences$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The number of bones in the adult human skeleton is$x$, $x$["186","196","206","216"]$x$, 2, $x$The adult skeleton has 206 bones, 80 axial and 126 appendicular. A newborn has around 300, many of which fuse during growth, which is why the adult count is lower.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (1, $x$The longest and strongest bone in the human body is the$x$, $x$["Fibula","Tibia","Humerus","Femur"]$x$, 3, $x$The femur is the longest, heaviest and strongest bone, transmitting body weight from the hip to the knee. A fractured femur can bleed one to one and a half litres into the thigh, enough to cause shock.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (2, $x$Bile is produced by the liver and stored and concentrated in the$x$, $x$["Gall bladder","Duodenum","Pancreas","Spleen"]$x$, 0, $x$Hepatocytes secrete bile continuously; the gall bladder stores and concentrates it and releases it when cholecystokinin is triggered by fat in the duodenum. Bile emulsifies fat rather than digesting it chemically.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (3, $x$Vitamin B12 is absorbed mainly in the$x$, $x$["Jejunum","Terminal ileum","Stomach","Duodenum"]$x$, 1, $x$Vitamin B12 binds intrinsic factor made by gastric parietal cells and the complex is absorbed in the terminal ileum. This is why both total gastrectomy and ileal resection or Crohn disease of the ileum cause B12 deficiency.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (4, $x$The pacemaker of the heart is the$x$, $x$["Bundle of His","Atrioventricular node","Purkinje fibres","Sinoatrial node"]$x$, 3, $x$The sinoatrial node in the right atrium discharges fastest, at 60 to 100 per minute, and so sets the rhythm. If it fails, the AV node takes over at 40 to 60 and the ventricles at 20 to 40, each progressively slower.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (5, $x$The hormone that raises blood calcium by acting on bone, kidney and gut is$x$, $x$["Parathyroid hormone","Aldosterone","Calcitonin","Insulin"]$x$, 0, $x$Parathyroid hormone raises serum calcium by mobilising it from bone, increasing renal reabsorption and activating vitamin D to increase gut absorption. Calcitonin from the thyroid parafollicular cells does the opposite and lowers calcium.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (6, $x$Cortisol is secreted by which layer of the adrenal gland?$x$, $x$["Zona glomerulosa","Zona reticularis","Zona fasciculata","Adrenal medulla"]$x$, 2, $x$The cortex has three zones: glomerulosa making aldosterone, fasciculata making cortisol and reticularis making androgens, remembered as salt, sugar and sex. The medulla is separate and secretes adrenaline and noradrenaline.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (7, $x$The normal serum potassium level in an adult is$x$, $x$["1.5 to 2.5 mEq/L","3.5 to 5.0 mEq/L","7.0 to 8.5 mEq/L","10 to 12 mEq/L"]$x$, 1, $x$Normal potassium is 3.5 to 5.0 mEq per litre and the margin for error is small, because both low and high levels cause fatal arrhythmias. Sodium sits far higher, at 135 to 145 mEq per litre.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (8, $x$The normal tidal volume in a healthy adult at rest is approximately$x$, $x$["150 mL","500 mL","1200 mL","2500 mL"]$x$, 1, $x$Tidal volume is about 500 mL, of which roughly 150 mL fills anatomical dead space and takes no part in gas exchange. Vital capacity, the largest volume that can be moved voluntarily, is around 4500 mL.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (9, $x$Adequate urine output in an adult is generally taken as$x$, $x$["At least 50 mL per hour regardless of weight","At least 0.5 mL per kilogram per hour","At least 5 mL per kilogram per hour","At least 200 mL per hour"]$x$, 1, $x$A minimum of 0.5 mL/kg/hour, roughly 30 mL per hour in an average adult, indicates adequate renal perfusion. Falling below this is one of the earliest and most useful warnings of hypovolaemia.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (10, $x$A person with blood group O negative is described as a universal$x$, $x$["Recipient","Donor","Neither","Both donor and recipient"]$x$, 1, $x$O negative red cells carry neither A, B nor RhD antigen, so they can be given to almost anyone, making O negative the universal red cell donor. AB positive is the universal recipient, having no anti-A or anti-B antibodies.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (11, $x$Baroreceptors that help regulate blood pressure are located in the$x$, $x$["Hypothalamus","Carotid sinus and aortic arch","Lung alveoli","Renal tubules"]$x$, 1, $x$Stretch receptors in the carotid sinus and aortic arch sense arterial pressure and signal the medulla, which adjusts heart rate and vessel tone within seconds. Chemoreceptors nearby respond instead to oxygen, carbon dioxide and pH.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (12, $x$The normal haemoglobin range for an adult woman is approximately$x$, $x$["6 to 8 g/dL","12 to 15 g/dL","18 to 20 g/dL","22 to 25 g/dL"]$x$, 1, $x$Adult women normally run 12 to 15 g/dL and men 13 to 17 g/dL. WHO defines anaemia as below 12 g/dL in non-pregnant women and below 11 g/dL in pregnancy.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (13, $x$The normal platelet count is$x$, $x$["150,000 to 400,000 per microlitre","15,000 to 40,000 per microlitre","1.5 to 4 million per microlitre","15 to 40 million per microlitre"]$x$, 0, $x$Normal platelets are 150,000 to 400,000 per microlitre. Spontaneous bleeding becomes a real risk below about 20,000, and surgery is usually deferred below 50,000.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (14, $x$Which clotting factors depend on vitamin K for their synthesis?$x$, $x$["Factors I, V, VIII and XIII","Factors XI and XII only","Factors III, IV and VI","Factors II, VII, IX and X"]$x$, 3, $x$Factors II, VII, IX and X, together with proteins C and S, require vitamin K for carboxylation in the liver. Warfarin blocks this step, which explains both its action and why vitamin K reverses it.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (15, $x$Spermatogenesis requires a testicular temperature that is$x$, $x$["Independent of temperature","Equal to core body temperature","Two to three degrees below core body temperature","Two to three degrees above core body temperature"]$x$, 2, $x$The scrotum holds the testes a few degrees below core temperature, which normal sperm production requires. Undescended testes remain at body temperature and, if not corrected early, lead to infertility and a raised risk of malignancy.$x$, $x$Basic Sciences$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 07-medical-surgical-2.txt — 20 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 7 — Medical-Surgical Nursing, second set$x$, $x$Medical-Surgical Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The classic triad of diabetic ketoacidosis is$x$, $x$["Hyperglycaemia, ketosis and metabolic acidosis","Hyperglycaemia, hypernatraemia and alkalosis","Normal glucose with ketosis","Hypoglycaemia, ketosis and alkalosis"]$x$, 0, $x$DKA is defined by high blood glucose, ketones in blood or urine and a metabolic acidosis with a low bicarbonate. Deep sighing Kussmaul respiration and an acetone smell on the breath are the bedside clues.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (1, $x$The first action for a conscious patient showing sweating, tremor and confusion with a capillary glucose of 45 mg/dL is$x$, $x$["Give 15 to 20 grams of fast-acting oral glucose and recheck in 15 minutes","Give intravenous insulin","Withhold all food until the doctor arrives","Encourage the patient to walk it off"]$x$, 0, $x$This is hypoglycaemia and it is treated immediately by mouth if the patient is conscious and able to swallow, then rechecked after 15 minutes and followed by a complex carbohydrate. Insulin would be catastrophic, and an unconscious patient needs intravenous dextrose or glucagon instead.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (2, $x$In an acute adrenal crisis, the priority treatment is$x$, $x$["Diuretics","Oral steroids the next morning","Insulin infusion","Intravenous hydrocortisone with fluid and glucose replacement"]$x$, 3, $x$Addisonian crisis presents with hypotension, hyponatraemia, hyperkalaemia and hypoglycaemia and is treated with immediate intravenous hydrocortisone alongside saline and dextrose. Delay is fatal, so treatment precedes confirmatory testing.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (3, $x$The Rule of Nines is used to estimate$x$, $x$["Percentage of total body surface area burned","Level of consciousness","Depth of a burn","Fluid output"]$x$, 0, $x$The Rule of Nines divides the adult body into multiples of nine per cent: head 9, each arm 9, each leg 18, front of trunk 18, back 18 and perineum 1. Children have proportionally larger heads, so the Lund and Browder chart is more accurate for them.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (4, $x$Using the Parkland formula, the fluid requirement in the first 24 hours after a burn is$x$, $x$["2 mL times body weight in kg times percentage burn","4 mL times body weight in kg times percentage burn","6 mL times body weight in kg times percentage burn","10 mL times body weight in kg times percentage burn"]$x$, 1, $x$Parkland gives 4 mL of Ringer lactate per kilogram per per cent burn over 24 hours, with half in the first 8 hours from the time of injury and the remainder over the following 16. The formula is only a starting estimate; urine output guides the actual rate.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (5, $x$The earliest and most reliable sign of compartment syndrome is$x$, $x$["Pain out of proportion to the injury, worse on passive stretch","Absent distal pulse","Paralysis","Pallor of the limb"]$x$, 0, $x$Severe pain, worsened by passively stretching the muscles in the compartment, appears long before the other Ps. Pulselessness and paralysis are very late, and waiting for them means the limb is already being lost.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (6, $x$The mnemonic FAST for recognising stroke stands for$x$, $x$["Face, Arms, Speech, Time","Fluid, Assessment, Support, Transfer","Function, Ability, Sensation, Tone","Fever, Airway, Signs, Treatment"]$x$, 0, $x$Facial droop, arm weakness and speech disturbance signal a possible stroke, and Time emphasises that thrombolysis is only possible within a narrow window. Noting the exact time the patient was last seen well is a crucial nursing observation.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (7, $x$During a generalised tonic-clonic seizure the nurse should$x$, $x$["Insert a padded tongue depressor into the mouth","Give oral medication immediately","Protect the head, loosen tight clothing and turn the patient to the side once movements settle","Restrain the limbs firmly"]$x$, 2, $x$Care is protective rather than interventional: prevent injury, do not restrain, and place the patient in the recovery position afterwards to protect the airway. Forcing anything into the mouth breaks teeth and risks obstruction.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (8, $x$A patient develops fever, chills, loin pain and dark urine 15 minutes into a blood transfusion. The nurse should first$x$, $x$["Slow the transfusion and continue observing","Give an antipyretic and continue","Stop the transfusion, keep the line open with normal saline through fresh tubing, and inform the doctor","Remove the cannula completely"]$x$, 2, $x$These features suggest an acute haemolytic reaction from ABO incompatibility. The transfusion is stopped at once but venous access is preserved with saline through new tubing, and the unit and samples are returned to the blood bank for investigation.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (9, $x$The most common site of a peptic ulcer associated with Helicobacter pylori is the$x$, $x$["Oesophagus","Colon","Duodenum","Jejunum"]$x$, 2, $x$Duodenal ulcers are strongly associated with H. pylori and classically give pain relieved by food. Gastric ulcer pain tends to be worsened by eating, and treatment for both centres on eradication therapy plus acid suppression.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (10, $x$Asterixis, or flapping tremor, in a patient with cirrhosis suggests$x$, $x$["Simple fatigue","Iron overload","Hypoglycaemia","Hepatic encephalopathy from rising ammonia"]$x$, 3, $x$Asterixis is an early sign of hepatic encephalopathy as nitrogenous waste accumulates. Treatment reduces ammonia production with lactulose and rifaximin, and precipitants such as gastrointestinal bleeding, infection and constipation are sought.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (11, $x$Cullen sign and Grey Turner sign are associated with$x$, $x$["Renal colic","Acute appendicitis","Peptic ulcer","Severe haemorrhagic pancreatitis"]$x$, 3, $x$Cullen sign is periumbilical bruising and Grey Turner sign is flank bruising, both from retroperitoneal bleeding in severe pancreatitis. They are uncommon but indicate a serious course.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (12, $x$McBurney point tenderness is characteristic of$x$, $x$["Pancreatitis","Acute appendicitis","Cholecystitis","Diverticulitis"]$x$, 1, $x$McBurney point lies one third of the way from the right anterior superior iliac spine to the umbilicus and is the classic site of maximal tenderness in appendicitis. Heat and laxatives are avoided because they increase the risk of perforation.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (13, $x$Immediately after a below-knee amputation, the nurse should be most alert for$x$, $x$["Constipation","Haemorrhage from the stump","Phantom limb sensation","Loss of appetite"]$x$, 1, $x$Bleeding is the immediate postoperative danger, so the stump and dressing are observed closely and a tourniquet is kept at the bedside. Phantom sensation is common and distressing but is not an emergency.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (14, $x$The stoma of a healthy colostomy should appear$x$, $x$["Pale and dry","Bright yellow","Dark purple or black","Pink to red, moist and slightly raised"]$x$, 3, $x$A healthy stoma is pink or red and moist, like the inside of the cheek. Dusky purple or black indicates ischaemia and must be reported at once, and the surrounding skin is protected because effluent quickly excoriates it.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (15, $x$A patient receiving chemotherapy has an absolute neutrophil count of 400 per microlitre. The priority nursing action is$x$, $x$["Institute neutropenic precautions and monitor closely for any sign of infection","Encourage visitors to cheer the patient up","Take rectal temperatures four hourly","Serve raw salad and fresh fruit juice"]$x$, 0, $x$Severe neutropenia leaves the patient unable to mount normal signs of infection, so fever alone is an emergency. Precautions include hand hygiene, avoiding crowds and uncooked foods, and avoiding rectal thermometers and suppositories, which can breach the mucosa.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (16, $x$The most effective measure to prevent deep vein thrombosis in a postoperative patient is$x$, $x$["Strict bed rest","Massaging the calves","Early mobilisation, with graduated compression stockings and prophylactic anticoagulation as prescribed","Restricting fluids"]$x$, 2, $x$Immobility is the main risk, so early mobilisation and leg exercises, mechanical prophylaxis and low molecular weight heparin are used together. Calves are never massaged when thrombosis is suspected, because a clot may embolise.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (17, $x$The most common healthcare associated infection linked to an indwelling device is$x$, $x$["Fungal nail infection","Conjunctivitis","Surgical site infection of the scalp","Catheter associated urinary tract infection"]$x$, 3, $x$Urinary catheters account for a large share of hospital infection, and risk rises with every extra day in place. The most effective prevention is avoiding unnecessary catheters and removing them as early as possible, alongside a closed drainage system kept below bladder level.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (18, $x$When suctioning a tracheostomy, suction should be applied$x$, $x$["For a full minute at a time","Continuously while inserting the catheter","Only after instilling 10 mL of saline","Only while withdrawing the catheter, for no more than 10 to 15 seconds"]$x$, 3, $x$Suction is applied intermittently on withdrawal and limited to 10 to 15 seconds, with pre-oxygenation, because suctioning removes oxygen as well as secretions. Routine saline instillation is no longer recommended, as it does not thin secretions and may push organisms downward.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (19, $x$A patient with a chest injury shows tracheal deviation away from the affected side, absent breath sounds and rapidly worsening shock. This suggests$x$, $x$["Tension pneumothorax","Pulmonary oedema","Pleural effusion","Simple pneumothorax"]$x$, 0, $x$Air trapped under pressure shifts the mediastinum, kinks the great vessels and collapses venous return, giving obstructive shock. It is a clinical diagnosis needing immediate needle decompression followed by a chest drain, not an X-ray first.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 08-obg-child-2.txt — 24 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 8 — Obstetrics and Child Health, second set$x$, $x$Obstetrics & Child Health$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$A woman who has had three pregnancies and two live births is recorded as$x$, $x$["Gravida 5, para 3","Gravida 3, para 3","Gravida 2, para 3","Gravida 3, para 2"]$x$, 3, $x$Gravida counts all pregnancies including the current one, and para counts births after the age of viability. So three pregnancies with two births is gravida 3, para 2.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (1, $x$Painless bright red vaginal bleeding in the third trimester most suggests$x$, $x$["Abruptio placentae","Cervical polyp","Ruptured uterus","Placenta praevia"]$x$, 3, $x$Praevia bleeds painlessly because the low-lying placenta separates as the lower segment forms, and the uterus stays soft. Abruption gives painful bleeding with a tense tender uterus, and vaginal examination is avoided in suspected praevia until placental site is known.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (2, $x$The commonest site of an ectopic pregnancy is the$x$, $x$["Fallopian tube","Abdominal cavity","Cervix","Ovary"]$x$, 0, $x$About 95 per cent of ectopic pregnancies implant in the fallopian tube, most often the ampulla. The classic presentation is amenorrhoea, lower abdominal pain and spotting, and rupture causes sudden severe pain with shock.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (3, $x$Anti-D immunoglobulin is given to$x$, $x$["All mothers regardless of blood group","The newborn immediately after birth","Rh negative mothers who are not already sensitised, after delivery of an Rh positive baby or a sensitising event","Rh positive mothers with an Rh negative baby"]$x$, 2, $x$Anti-D destroys fetal red cells that have entered the maternal circulation before the mother can form her own antibodies, and is given within 72 hours of delivery or a sensitising event such as miscarriage or amniocentesis. It cannot help a mother who is already sensitised.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (4, $x$The partograph is used mainly to$x$, $x$["Assess the newborn at birth","Calculate the expected date of delivery","Record the antenatal history","Monitor the progress of labour and detect deviation early"]$x$, 3, $x$The partograph plots cervical dilatation against time together with fetal and maternal observations. Crossing the alert line signals slow progress and crossing the action line calls for definitive intervention.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (5, $x$Lochia rubra, serosa and alba normally appear in the order$x$, $x$["Whitish, then red, then brown","Brown, then white, then red","Red, then pink-brown, then whitish","They appear simultaneously"]$x$, 2, $x$Lochia rubra is red for about the first three to four days, becoming serosa, pinkish brown, for up to about ten days, and finally alba, whitish, for a further one to two weeks. A return to red bleeding or an offensive smell suggests retained products or infection.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (6, $x$The uterus normally returns to its pre-pregnant size by about$x$, $x$["Six weeks after delivery","One week after delivery","Three months after delivery","Six months after delivery"]$x$, 0, $x$Involution takes roughly six weeks, with the fundus descending about one centimetre a day and becoming impalpable abdominally by around ten days. A uterus that stays high and boggy suggests subinvolution.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (7, $x$Puerperal sepsis is defined as infection of the genital tract occurring$x$, $x$["Only after caesarean section","During pregnancy only","Only in the first 24 hours","Any time from rupture of membranes or labour up to 42 days postpartum"]$x$, 3, $x$The definition covers infection from rupture of membranes or the onset of labour until 42 days after delivery, with fever, offensive lochia, uterine tenderness and delayed involution. It remains a leading direct cause of maternal death.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (8, $x$A woman in labour has a cord prolapse. The immediate nursing action is$x$, $x$["Apply a tight vaginal pack","Ask the woman to sit upright and push","Relieve pressure on the cord by positioning, keep it warm and moist, and call for immediate delivery","Push the cord back into the uterus"]$x$, 2, $x$The cord must not be handled or replaced, as this causes spasm. The presenting part is lifted off the cord, the woman is placed knee-chest or in exaggerated Sims position with the hips raised, and preparations are made for immediate caesarean section.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (9, $x$The copper-bearing intrauterine device works chiefly by$x$, $x$["Blocking the fallopian tubes mechanically","Preventing ovulation entirely","Creating a local inflammatory and spermicidal environment that prevents fertilisation","Suppressing pituitary hormones"]$x$, 2, $x$Copper ions are toxic to sperm and provoke a sterile inflammatory reaction in the endometrium, preventing fertilisation. It does not reliably stop ovulation, and it offers no protection against sexually transmitted infection.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (10, $x$Combined oral contraceptive pills are generally contraindicated in a woman who$x$, $x$["Has mild dysmenorrhoea","Is breastfeeding a six-week-old baby or has a history of thromboembolism","Is 22 years old and nulliparous","Has irregular but ovulatory cycles"]$x$, 1, $x$Oestrogen raises the risk of venous thromboembolism and can reduce milk supply in early lactation, so progestogen-only methods are preferred in these situations. Smoking over the age of 35 and migraine with aura are other important contraindications.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (11, $x$The minimum number of antenatal visits recommended for a normal pregnancy under Indian national guidance is$x$, $x$["Four","Two","Ten","One"]$x$, 0, $x$At least four visits are recommended, the first in the first trimester, with WHO now advising eight contacts for better outcomes. Each visit checks weight, blood pressure, urine, haemoglobin, fundal height and fetal heart, along with tetanus prophylaxis and iron and folic acid.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (12, $x$Kangaroo mother care involves$x$, $x$["Continuous skin-to-skin contact on the mother's chest with exclusive breastfeeding","Feeding by nasogastric tube only","Nursing the baby in an incubator at all times","Isolating the baby from the mother"]$x$, 0, $x$Skin-to-skin contact stabilises the baby's temperature, heart rate and breathing, promotes breastfeeding and bonding, and reduces infection and mortality in low birth weight babies. It is effective, and free.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (13, $x$A baby weighing less than 2500 grams at birth is classified as$x$, $x$["Normal weight","Extremely low birth weight","Low birth weight","Very low birth weight"]$x$, 2, $x$Low birth weight is under 2500 grams, very low under 1500 and extremely low under 1000. Low birth weight results either from prematurity or from intrauterine growth restriction, and the distinction matters for management.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (14, $x$A healthy infant can usually sit without support by about$x$, $x$["2 months","4 months","6 to 8 months","15 months"]$x$, 2, $x$Sitting without support comes at around six to eight months, standing with support at about nine, and independent walking between twelve and fifteen months. Not walking by eighteen months warrants assessment.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (15, $x$Complementary feeding should be started at$x$, $x$["2 months","4 months","6 months","12 months"]$x$, 2, $x$Breast milk alone no longer meets energy and iron needs after six months, so semi-solid complementary foods begin then while breastfeeding continues. Starting earlier displaces breast milk and raises infection risk; starting later risks growth faltering.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (16, $x$The current WHO oral rehydration solution is described as$x$, $x$["Reduced osmolarity, containing sodium, potassium, chloride, citrate and glucose","High osmolarity with high sodium","Sodium bicarbonate solution alone","Plain glucose water"]$x$, 0, $x$The reduced osmolarity formula lowers stool output, vomiting and the need for intravenous fluids compared with the older solution. Glucose is essential because sodium absorption in the gut is coupled to glucose transport.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (17, $x$Under the national programme, vitamin A prophylaxis for children is given$x$, $x$["Daily from birth","Once in a lifetime","Every six months from nine months up to five years","Only when night blindness appears"]$x$, 2, $x$The first dose accompanies measles vaccination at nine months, then 200,000 IU every six months until five years, for a total of nine doses. Vitamin A deficiency remains a leading preventable cause of childhood blindness and worsens measles and diarrhoea.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (18, $x$Tetralogy of Fallot consists of pulmonary stenosis, overriding aorta, right ventricular hypertrophy and$x$, $x$["Atrial septal defect","Coarctation of the aorta","Ventricular septal defect","Patent ductus arteriosus"]$x$, 2, $x$The fourth component is a ventricular septal defect. It is the commonest cyanotic congenital heart disease beyond infancy, and children characteristically squat during hypercyanotic spells because it raises systemic resistance and improves pulmonary flow.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (19, $x$The classic presentation of nephrotic syndrome in a child is$x$, $x$["Heavy proteinuria, hypoalbuminaemia, oedema and hyperlipidaemia","Fever with dysuria only","Polyuria and weight loss","Haematuria, hypertension and oliguria with minimal protein"]$x$, 0, $x$Nephrotic syndrome is dominated by protein loss, giving low albumin, generalised oedema often first noticed as puffy eyelids, and raised lipids. The nephritic picture, by contrast, is dominated by haematuria, hypertension and reduced output.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (20, $x$A child with acute epiglottitis should not$x$, $x$["Be kept calm and upright","Receive oxygen","Be taken to theatre for airway assessment","Have the throat examined with a spatula"]$x$, 3, $x$Examining the throat can provoke complete airway obstruction. The child is kept calm, upright and undisturbed, ideally with a parent, while senior anaesthetic and ENT help is summoned to secure the airway.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (21, $x$Rheumatic fever most commonly follows infection with$x$, $x$["Staphylococcus aureus","Candida albicans","Group A beta-haemolytic Streptococcus","Escherichia coli"]$x$, 2, $x$Rheumatic fever follows a throat infection with group A Streptococcus by two to three weeks, through an immune cross-reaction that can permanently damage heart valves. Treating streptococcal sore throat properly is the primary prevention.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (22, $x$The Apgar score is routinely assessed at$x$, $x$["1 and 5 minutes after birth","At 24 hours","Only at 10 minutes","Every hour for six hours"]$x$, 0, $x$The score is taken at one and five minutes, and repeated every five minutes up to twenty if it remains below seven. It describes the transition to extrauterine life and should never delay resuscitation, which begins on clinical assessment.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (23, $x$A newborn's temperature is best maintained immediately after birth by$x$, $x$["Drying thoroughly, removing wet linen and placing skin to skin under a warm cover","Leaving the baby uncovered under a fan","Placing the baby directly on a cold surface","Bathing the baby at once"]$x$, 0, $x$Newborns lose heat rapidly by evaporation, conduction, convection and radiation. Drying and removing wet cloth, skin-to-skin contact and covering the head prevent hypothermia, and the first bath is delayed for at least 24 hours.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 09-community-mental-2.txt — 20 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 9 — Community Health and Mental Health, second set$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$In the plains, one sub-centre in India is established for a population of about$x$, $x$["1000","5000","30000","100000"]$x$, 1, $x$A sub-centre serves about 5000 people in the plains and 3000 in hilly, tribal or difficult areas. A primary health centre covers about 30,000 and 20,000 respectively, and a community health centre about 120,000.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (1, $x$The crude birth rate is expressed as the number of live births per$x$, $x$["100000 women","1000 live births","1000 mid-year population","100 population"]$x$, 2, $x$Crude birth rate uses the mid-year population as its denominator. It is called crude because it takes no account of age or sex structure, unlike the general fertility rate which uses women of reproductive age.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (2, $x$Case fatality rate measures$x$, $x$["Deaths in the whole population","The number of new cases in a year","The number of existing cases at a point in time","Deaths from a disease among those who have that disease"]$x$, 3, $x$Case fatality rate is deaths from a disease divided by the number of diagnosed cases, expressing the virulence of that disease. Incidence counts new cases over a period and prevalence counts all existing cases at a point.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (3, $x$The ability of a screening test to correctly identify those who truly have the disease is its$x$, $x$["Specificity","Predictive value","Sensitivity","Reliability"]$x$, 2, $x$Sensitivity is the proportion of true cases the test detects, so a highly sensitive test produces few false negatives and is preferred for screening. Specificity is the ability to correctly exclude those without the disease.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (4, $x$The incubation period of a disease is the interval between$x$, $x$["Two successive cases in a chain of transmission","Exposure to the agent and the appearance of the first symptoms","Diagnosis and treatment","Onset of symptoms and recovery"]$x$, 1, $x$Incubation runs from entry of the organism to the first clinical signs. The generation time, by contrast, is the interval between successive cases and matters more when tracking an outbreak.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (5, $x$Under the ICDS scheme, services are delivered mainly through the$x$, $x$["Private clinic","Medical college","District hospital","Anganwadi centre"]$x$, 3, $x$The Integrated Child Development Services scheme works through the anganwadi centre and worker, providing supplementary nutrition, immunisation, health check-ups, referral, pre-school education and nutrition and health education to children under six and to pregnant and nursing mothers.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (6, $x$Janani Suraksha Yojana was introduced primarily to$x$, $x$["Fund medical education","Provide free medicines to the elderly","Supply drinking water","Promote institutional delivery through conditional cash assistance"]$x$, 3, $x$JSY gives cash assistance to encourage delivery in a health facility, aiming to reduce maternal and neonatal mortality. It works alongside the ASHA, who accompanies the mother and receives a linked incentive.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (7, $x$Universal salt iodisation is the main strategy against$x$, $x$["Iron deficiency anaemia","Protein energy malnutrition","Iodine deficiency disorders including goitre and cretinism","Vitamin A deficiency"]$x$, 2, $x$Iodised salt is the cornerstone of prevention, with iodine content specified at production and at the household level. Deficiency in pregnancy causes irreversible mental impairment in the child, which is why prevention rather than treatment is the goal.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (8, $x$Sterilisation as a family planning method is best described as$x$, $x$["Requiring daily action by the user","Effective only in women","Permanent, with tubectomy for women and vasectomy for men","Temporary and easily reversible"]$x$, 2, $x$Tubectomy and vasectomy are permanent methods and should be chosen only when the family is complete. Vasectomy is simpler, safer and cheaper, but a man remains fertile until the stored sperm are cleared, so another method is needed for about three months.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (9, $x$A disease that must be reported to public health authorities by law is termed$x$, $x$["Notifiable","Idiopathic","Sporadic","Endemic"]$x$, 0, $x$Notifiable diseases such as cholera, tuberculosis and measles must be reported so that outbreaks can be detected and controlled. Prompt notification by nursing staff is often the first step in an outbreak response.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (10, $x$The most effective household method of making water bacteriologically safe where fuel is available is$x$, $x$["Adding alum only","Storing in a covered pot for a day","Filtering through a cloth","Boiling for a rolling boil of several minutes"]$x$, 3, $x$Boiling kills bacteria, viruses and cysts reliably. Alum only helps sedimentation of suspended matter, and cloth filtration removes larger particles and cyclops but not bacteria.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (11, $x$Primary health care as defined at Alma-Ata rests on principles that include$x$, $x$["Payment at the point of care","Care limited to hospitals","Treatment by specialists only","Equitable distribution, community participation, intersectoral coordination and appropriate technology"]$x$, 3, $x$The four pillars are equitable distribution, community participation, intersectoral coordination and appropriate technology, with prevention emphasised over cure. They remain the framework for national health policy.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (12, $x$Panic level anxiety is characterised by$x$, $x$["Mild restlessness only","Disorganised behaviour, distorted perception and inability to function","Narrowed perception with some ability to focus if directed","Heightened alertness and improved learning"]$x$, 1, $x$Anxiety runs from mild, which sharpens attention, through moderate and severe with progressively narrowing perception, to panic, where the person cannot process the environment or act purposefully and needs a calm presence and a safe, quiet setting.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (13, $x$Obsessive-compulsive disorder is characterised by$x$, $x$["Loss of memory for personal identity","Hearing voices that others cannot hear","Recurrent intrusive thoughts recognised as one's own, with repetitive acts performed to reduce anxiety","Fixed false beliefs held with conviction"]$x$, 2, $x$The person knows the thoughts are their own and senseless but cannot dismiss them, and rituals relieve anxiety only briefly. This insight distinguishes obsessions from delusions.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (14, $x$A patient in an acute manic episode is best nursed by$x$, $x$["Encouraging participation in competitive group games","Leaving the patient unobserved to burn off energy","Confronting grandiose statements directly and arguing","Providing a calm low-stimulus environment, finger foods and short frequent contacts"]$x$, 3, $x$Overstimulation worsens mania, and the patient is often too restless to sit for meals, so portable high-calorie finger foods maintain nutrition. Arguing about grandiosity provokes hostility; setting firm consistent limits works better.$x$, $x$Mental Health Nursing$x$, $x$hard$x$),
  (15, $x$Delirium tremens following alcohol withdrawal typically appears$x$, $x$["Within one hour of the last drink","Two weeks later","Between 48 and 96 hours after the last drink","Only after six months of abstinence"]$x$, 2, $x$Tremor and agitation begin within about 6 to 24 hours, but delirium tremens with confusion, vivid hallucinations, fever and autonomic instability peaks at two to four days and can be fatal. Benzodiazepines and thiamine are the mainstays of management.$x$, $x$Mental Health Nursing$x$, $x$hard$x$),
  (16, $x$Wernicke encephalopathy in chronic alcohol use is caused by deficiency of$x$, $x$["Calcium","Vitamin C","Vitamin D","Thiamine"]$x$, 3, $x$Thiamine deficiency produces confusion, ataxia and eye signs, and thiamine must be given before any glucose load, since giving glucose first can precipitate the syndrome. Untreated it may progress to irreversible Korsakoff psychosis.$x$, $x$Mental Health Nursing$x$, $x$hard$x$),
  (17, $x$Physical restraint of a psychiatric patient is acceptable only when$x$, $x$["The ward is short staffed","A relative requests it","All less restrictive measures have failed and there is immediate risk of harm, with documentation and frequent review","The patient is uncooperative at mealtimes"]$x$, 2, $x$Restraint is a last resort, used for the shortest possible time to prevent harm, with the least restrictive method, continuous observation, attention to circulation, hydration and elimination, and clear documentation. It is never a substitute for staffing or a punishment.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (18, $x$Anorexia nervosa is characterised by$x$, $x$["Loss of appetite due to physical illness","Refusal to maintain body weight with intense fear of gaining weight and disturbed body image","Craving for non-food substances","Episodes of overeating followed by guilt but normal weight"]$x$, 1, $x$The core features are self-imposed starvation, intense fear of weight gain and a distorted perception of body size, with amenorrhoea and dangerous cardiac and electrolyte complications. Craving non-food substances is pica.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (19, $x$The Mental Healthcare Act 2017 in India is notable for$x$, $x$["Removing all rights from persons with mental illness","Making institutional admission compulsory","Recognising the right to access mental healthcare and effectively decriminalising attempted suicide","Banning community treatment"]$x$, 2, $x$The Act asserts a right to access affordable mental healthcare, allows advance directives and nominated representatives, and presumes that a person attempting suicide is under severe stress, so they are not punished. It represents a decisive shift towards rights-based care.$x$, $x$Mental Health Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 10-pharma-fundamentals-2.txt — 21 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 10 — Pharmacology, Fundamentals, Microbiology, Research and Management$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The half-life of a drug is the time taken for$x$, $x$["The plasma concentration to fall by half","The drug to reach peak concentration","The drug to be fully absorbed","The drug to be completely eliminated"]$x$, 0, $x$Half-life is the time for plasma concentration to halve, and it determines dosing interval. It takes about four to five half-lives to eliminate a drug or, with regular dosing, to reach steady state.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (1, $x$First-pass metabolism refers to$x$, $x$["Binding of the drug to plasma proteins","Metabolism of an orally absorbed drug by the liver before it reaches the systemic circulation","The first dose given to a patient","Renal excretion of the drug"]$x$, 1, $x$Drugs absorbed from the gut travel through the portal vein and are partly metabolised by the liver before reaching the circulation, which is why oral doses are often much larger than parenteral ones. Sublingual, rectal and parenteral routes bypass this.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (2, $x$Early signs of digoxin toxicity include$x$, $x$["Hypertension and polyuria","Constipation and dry skin only","Anorexia, nausea, visual disturbance with yellow-green halos and bradycardia","Fever and rash"]$x$, 2, $x$Digoxin has a narrow therapeutic index and toxicity begins with gastrointestinal and visual symptoms alongside arrhythmias. Hypokalaemia, often from diuretics, markedly increases the risk, so potassium is watched closely.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (3, $x$A patient on long-term oral corticosteroids must be taught never to$x$, $x$["Stop the drug abruptly","Report signs of infection","Take the dose in the morning","Take it with food"]$x$, 0, $x$Prolonged steroids suppress the hypothalamic-pituitary-adrenal axis, so sudden withdrawal can precipitate an adrenal crisis. The dose is tapered gradually, and morning dosing with food better mimics natural secretion and protects the stomach.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (4, $x$The Z-track technique of intramuscular injection is used to$x$, $x$["Speed up absorption","Prevent the drug leaking back into subcutaneous tissue and staining the skin","Allow a larger volume in the deltoid","Make the injection painless"]$x$, 1, $x$Displacing the skin laterally before injecting and releasing it afterwards seals the needle track. It is used for irritant or staining preparations such as iron dextran.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (5, $x$Salbutamol given by nebuliser commonly causes$x$, $x$["Bradycardia and drowsiness","Hearing loss","Tremor, tachycardia and palpitations","Constipation"]$x$, 2, $x$As a beta-2 agonist with some beta-1 effect, salbutamol causes fine tremor, tachycardia and occasionally hypokalaemia. Patients should be warned these effects are expected and usually settle.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (6, $x$Blood samples for culture should ideally be taken$x$, $x$["Before starting antibiotic therapy","Only after the fever settles","After the first dose of antibiotic","At any time during the course"]$x$, 0, $x$Antibiotics given first may suppress growth and give a false negative, losing the chance to identify the organism and its sensitivities. Cultures are taken first, ideally at the peak of fever, and treatment then started promptly.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (7, $x$A patient weighing 60 kg is prescribed a drug at 5 mg per kg per day, in two divided doses. Each dose is$x$, $x$["60 mg","150 mg","300 mg","600 mg"]$x$, 1, $x$The total daily dose is 5 multiplied by 60, which is 300 mg, and divided into two doses gives 150 mg per dose. Reading whether the figure quoted is per day or per dose is where most calculation errors happen.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (8, $x$A nasal cannula at 2 litres per minute delivers an approximate inspired oxygen concentration of$x$, $x$["21 per cent","28 per cent","60 per cent","100 per cent"]$x$, 1, $x$Each litre per minute adds roughly 4 per cent above room air, so 2 litres gives about 28 per cent, though the true value varies with the patient's breathing pattern. A non-rebreather mask with a reservoir delivers the highest concentration.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (9, $x$The recommended duration for routine handwashing with soap and water is at least$x$, $x$["5 seconds","5 minutes","40 to 60 seconds","10 minutes"]$x$, 2, $x$WHO advises 40 to 60 seconds for soap and water and 20 to 30 seconds for an alcohol-based handrub, covering all surfaces including thumbs, fingertips and between the fingers. Technique matters as much as duration.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (10, $x$In the semi-Fowler position the head of the bed is elevated to about$x$, $x$["15 degrees","30 to 45 degrees","60 degrees","90 degrees"]$x$, 1, $x$Semi-Fowler is 30 to 45 degrees, Fowler about 45 to 60 and high Fowler 60 to 90. Elevating the head aids breathing and, in a ventilated or tube-fed patient, reduces the risk of aspiration.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (11, $x$When establishing a sterile field, an item is considered contaminated if it is$x$, $x$["Below waist level or out of the field of vision","Held above waist level","Handled with sterile gloves","In the centre of the field"]$x$, 0, $x$Anything below the waist or out of sight is treated as unsterile, as is the one-inch border of a sterile drape and any wet field, since moisture wicks organisms upward. When in doubt, an item is considered contaminated.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (12, $x$Pain is often described as the fifth vital sign because$x$, $x$["It can be measured with a thermometer","It should be assessed and documented routinely, using the patient's own report","It is always visible to the nurse","It correlates exactly with blood pressure"]$x$, 1, $x$Pain is subjective, and the patient's self-report is the most reliable indicator. Routine assessment with an appropriate scale, and reassessment after intervention, is what turns pain relief into measurable care.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (13, $x$When lifting a heavy object, correct body mechanics require the nurse to$x$, $x$["Bend the knees, keep the back straight and hold the load close to the body","Bend at the waist with straight legs","Twist while lifting","Lift quickly with a jerk"]$x$, 0, $x$Using the strong leg muscles with a wide base of support, keeping the load close and turning the feet instead of twisting the spine protects the back. Back injury is one of the commonest occupational hazards in nursing.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (14, $x$Immediately after a needlestick injury from a patient's used needle, the nurse should first$x$, $x$["Squeeze the wound vigorously and apply spirit","Ignore it if the patient looks healthy","Wash the area with soap and running water, then report and seek post-exposure evaluation urgently","Apply a tourniquet above the site"]$x$, 2, $x$The wound is washed with soap and running water and the incident reported at once, because post-exposure prophylaxis for HIV is most effective when started within hours. Squeezing or applying caustic agents damages tissue without reducing risk.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (15, $x$Which organism is the commonest cause of surgical site infection?$x$, $x$["Plasmodium vivax","Candida albicans","Entamoeba histolytica","Staphylococcus aureus"]$x$, 3, $x$Staphylococcus aureus, often carried in the patient's own nose and skin, is the leading cause. This is why skin preparation, aseptic technique and appropriately timed prophylactic antibiotics matter so much.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (16, $x$The main purpose of a pilot study is to$x$, $x$["Publish preliminary conclusions","Replace the main study","Prove the hypothesis","Test feasibility of the method and tools on a small scale before the main study"]$x$, 3, $x$A pilot study checks whether the design, tools and procedures work, how long data collection takes and what problems arise, so they can be corrected. It is not powered to test the hypothesis and its subjects are excluded from the main sample.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (17, $x$Reliability of a research tool refers to$x$, $x$["Whether the study is ethical","Whether it measures what it is intended to measure","Whether it gives consistent results on repeated measurement","Whether the sample is large enough"]$x$, 2, $x$Reliability is consistency and validity is accuracy. A weighing scale reading three kilograms too heavy every time is perfectly reliable but not valid, which is why both must be established.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (18, $x$In an experimental study of the effect of an exercise programme on blood pressure, the independent variable is$x$, $x$["The age of the participants","The exercise programme","The sample size","Blood pressure"]$x$, 1, $x$The independent variable is what the researcher manipulates, here the exercise programme, and the dependent variable is the outcome measured, here blood pressure. Age would be an extraneous variable to be controlled.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (19, $x$A nursing audit is best described as$x$, $x$["A systematic review of nursing records and practice against agreed standards to improve care","A financial inspection of the ward budget","A survey of patient satisfaction only","A disciplinary enquiry into an individual nurse"]$x$, 0, $x$Audit compares actual practice with an agreed standard, identifies gaps and closes them by changing practice and re-auditing. Its purpose is improvement of the system, not blame of an individual.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (20, $x$Democratic or participative leadership in a nursing unit is characterised by$x$, $x$["Decisions taken solely by the manager without consultation","Involving staff in decision-making while the leader retains accountability","Decisions taken by an external authority","Complete absence of guidance"]$x$, 1, $x$Participative leadership consults the team and encourages ownership, which suits experienced staff and improves morale. Autocratic style is faster and appropriate in emergencies, while laissez-faire offers little direction and suits only highly self-directed teams.$x$, $x$Nursing Foundations$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

commit;

-- Expect: 101 rows inserted across 5 batches.
-- Check with:  select topic, difficulty, count(*) from questions group by 1,2 order by 1,2;
