-- ═══════════════════════════════════════════════════════
-- Question bank import
-- Run in: Supabase → SQL Editor → New query → Run
--
-- Wrapped in a transaction: if any row fails, nothing is
-- inserted and the bank is left exactly as it was.
-- Running it twice inserts the questions twice, so run once.
-- ═══════════════════════════════════════════════════════

begin;

-- 14-basic-sciences-2.txt — 30 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-basic — ingested draft, verify before trusting$x$, $x$Basic Sciences$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$Which of the following is an example of a hinge joint?$x$, $x$["Wrist joint","Elbow joint","Atlanto-axial joint","Shoulder joint"]$x$, 1, $x$Hinge joints permit movement in a single plane of flexion and extension, and the elbow is a classic example. The shoulder is a ball-and-socket joint, the atlanto-axial is a pivot joint, and the wrist is a condyloid joint.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (1, $x$The structural and functional unit of compact bone is the$x$, $x$["Osteon or Haversian system","Lamella","Osteocyte","Trabecula"]$x$, 0, $x$The osteon, or Haversian system, is the structural unit of compact bone and consists of concentric lamellae surrounding a central Haversian canal. Trabeculae are the corresponding units of spongy cancellous bone.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (2, $x$In a myelinated nerve fibre the action potential jumps between the nodes of Ranvier. This rapid mode of conduction is called$x$, $x$["Antidromic conduction","Decremental conduction","Continuous conduction","Saltatory conduction"]$x$, 3, $x$In myelinated axons the myelin insulates the internodal segments, so the impulse leaps from one node of Ranvier to the next, called saltatory conduction. This greatly increases the speed of nerve conduction.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (3, $x$How many cervical vertebrae are present in the human vertebral column?$x$, $x$["4","5","7","12"]$x$, 2, $x$The vertebral column contains 7 cervical vertebrae, followed by 12 thoracic, 5 lumbar, the fused sacrum, and the coccyx. Almost all mammals, regardless of neck length, share the count of seven cervical vertebrae.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (4, $x$The neurotransmitter released at the neuromuscular junction of skeletal muscle is$x$, $x$["Noradrenaline","GABA","Acetylcholine","Dopamine"]$x$, 2, $x$Motor neurons release acetylcholine at the neuromuscular junction, where it binds nicotinic receptors on the muscle end plate to trigger contraction. Noradrenaline, dopamine and GABA act at other sites in the nervous system.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (5, $x$The chemical transmitter released by most postganglionic sympathetic nerve endings is$x$, $x$["Acetylcholine","Noradrenaline","Adrenaline","Serotonin"]$x$, 1, $x$Most postganglionic sympathetic fibres are adrenergic and release noradrenaline. Exceptions such as sweat glands are cholinergic, while all preganglionic sympathetic fibres and all parasympathetic fibres release acetylcholine.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (6, $x$The photoreceptors of the retina responsible for vision in dim light are the$x$, $x$["Ganglion cells","Cones","Rods","Bipolar cells"]$x$, 2, $x$Rods contain the pigment rhodopsin and are highly sensitive to low light, mediating night or scotopic vision but not colour. Cones function in bright light and are responsible for colour and sharp central vision.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (7, $x$The corticospinal or pyramidal tract of the spinal cord primarily carries$x$, $x$["Pain and temperature sensation","Proprioception and fine touch","Voluntary motor impulses","Autonomic fibres"]$x$, 2, $x$The corticospinal tract is a descending pathway carrying voluntary motor commands from the motor cortex to spinal motor neurons. Pain and temperature travel in the spinothalamic tract, and fine touch and proprioception in the dorsal columns.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (8, $x$Which part of the inner ear is concerned with hearing?$x$, $x$["Utricle","Cochlea","Saccule","Semicircular canals"]$x$, 1, $x$The cochlea houses the organ of Corti, which converts sound vibrations into nerve impulses for hearing. The semicircular canals, utricle and saccule are parts of the vestibular apparatus concerned with balance and equilibrium.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (9, $x$The first heart sound, S1 or lubb, is produced by the closure of the$x$, $x$["Mitral and tricuspid atrioventricular valves","Aortic and pulmonary semilunar valves","Aortic valve only","Pulmonary valve only"]$x$, 0, $x$S1 is caused by closure of the atrioventricular mitral and tricuspid valves at the onset of ventricular systole. The second heart sound S2 results from closure of the semilunar aortic and pulmonary valves.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (10, $x$In a normal electrocardiogram, the P wave represents$x$, $x$["Ventricular depolarization","Atrial repolarization","Atrial depolarization","Ventricular repolarization"]$x$, 2, $x$The P wave represents atrial depolarization, the QRS complex represents ventricular depolarization, and the T wave represents ventricular repolarization. Atrial repolarization is normally hidden within the QRS complex.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (11, $x$The volume of air remaining in the lungs after a maximal forced expiration is called the$x$, $x$["Residual volume","Inspiratory reserve volume","Tidal volume","Vital capacity"]$x$, 0, $x$Residual volume is the air that cannot be expelled even after a maximal expiration, keeping the alveoli partly inflated. It is about 1200 mL and, because it cannot be exhaled, cannot be measured by ordinary spirometry.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (12, $x$The largest fraction of carbon dioxide is transported in the blood as$x$, $x$["Bicarbonate ions","Dissolved CO2 in plasma","Carbon monoxide","Carbaminohaemoglobin"]$x$, 0, $x$About 70 per cent of carbon dioxide is carried as bicarbonate ions formed in red cells by carbonic anhydrase. Roughly 23 per cent travels bound to haemoglobin as carbaminohaemoglobin, and only about 7 per cent is dissolved in plasma.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (13, $x$Pepsin, secreted by the gastric glands, acts on which class of nutrients?$x$, $x$["Proteins","Carbohydrates","Fats","Nucleic acids"]$x$, 0, $x$Pepsin is a gastric protease secreted as inactive pepsinogen and activated by hydrochloric acid; it begins protein digestion by cleaving peptide bonds. Carbohydrate digestion begins with salivary amylase and fat digestion mainly in the intestine.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (14, $x$Dietary iron is absorbed mainly in which part of the gastrointestinal tract?$x$, $x$["Duodenum","Terminal ileum","Colon","Stomach"]$x$, 0, $x$Iron is absorbed chiefly in the duodenum and upper jejunum, favoured by the acidic environment and by conversion to the ferrous form. The terminal ileum is the principal site for absorption of vitamin B12 and bile salts.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (15, $x$Almost all of the glucose filtered at the glomerulus is reabsorbed in the$x$, $x$["Loop of Henle","Collecting duct","Proximal convoluted tubule","Distal convoluted tubule"]$x$, 2, $x$Glucose is completely reabsorbed in the proximal convoluted tubule by sodium-glucose cotransporters under normal conditions. Glucose appears in the urine only when the plasma level exceeds the renal threshold of about 180 mg/dL.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (16, $x$Which hormone, secreted by the alpha cells of the pancreatic islets, raises blood glucose?$x$, $x$["Somatostatin","Insulin","Amylin","Glucagon"]$x$, 3, $x$Glucagon is secreted by the alpha cells of the islets of Langerhans and raises blood glucose by promoting hepatic glycogenolysis and gluconeogenesis. It is functionally antagonistic to insulin, which is produced by the beta cells.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (17, $x$Which mineral is an essential component of the thyroid hormone thyroxine?$x$, $x$["Iodine","Zinc","Calcium","Iron"]$x$, 0, $x$Iodine is an essential constituent of thyroid hormones; thyroxine T4 contains four iodine atoms and triiodothyronine T3 contains three. Dietary iodine deficiency impairs their synthesis and leads to goitre.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (18, $x$Ovulation in the human menstrual cycle is triggered by a mid-cycle surge of$x$, $x$["Progesterone","Oestrogen","Luteinizing hormone","Follicle-stimulating hormone"]$x$, 2, $x$A sharp mid-cycle surge of luteinizing hormone from the anterior pituitary triggers rupture of the mature Graafian follicle and release of the ovum. This surge is itself induced by rising peak levels of oestrogen.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (19, $x$The urea cycle, which converts toxic ammonia into urea, occurs mainly in the$x$, $x$["Kidney","Brain","Muscle","Liver"]$x$, 3, $x$The urea cycle operates primarily in hepatocytes, converting ammonia derived from amino acid deamination into non-toxic urea. The urea is then carried by the blood to the kidneys, which excrete it in the urine.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (20, $x$Beta-oxidation of fatty acids, which yields acetyl-CoA, takes place in the$x$, $x$["Mitochondrial matrix","Nucleus","Cytoplasm or cytosol","Endoplasmic reticulum"]$x$, 0, $x$Beta-oxidation occurs in the mitochondrial matrix, where fatty acyl-CoA is progressively shortened to yield acetyl-CoA along with NADH and FADH2. Fatty acid synthesis, by contrast, takes place in the cytosol.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (21, $x$The key rate-limiting or regulatory enzyme of glycolysis is$x$, $x$["Aldolase","Phosphofructokinase-1","Hexokinase","Pyruvate kinase"]$x$, 1, $x$Phosphofructokinase-1 catalyses the committed, rate-limiting step of glycolysis, converting fructose-6-phosphate to fructose-1,6-bisphosphate. It is allosterically inhibited by ATP and citrate and activated by AMP.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (22, $x$Deficiency of vitamin C or ascorbic acid causes which disease?$x$, $x$["Rickets","Beriberi","Pellagra","Scurvy"]$x$, 3, $x$Vitamin C is required for collagen synthesis, and its deficiency causes scurvy, marked by bleeding gums, poor wound healing and perifollicular haemorrhages. Beriberi results from thiamine deficiency and pellagra from niacin deficiency.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (23, $x$The most important buffer system of the extracellular fluid or plasma is the$x$, $x$["Protein buffer","Phosphate buffer","Bicarbonate-carbonic acid buffer","Ammonia buffer"]$x$, 2, $x$The bicarbonate-carbonic acid system is the principal buffer of extracellular fluid because its components are readily regulated: carbon dioxide by the lungs and bicarbonate by the kidneys. Phosphate and protein buffers act mainly within cells.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (24, $x$Bacteria that are spherical in shape are called$x$, $x$["Vibrios","Spirilla","Bacilli","Cocci"]$x$, 3, $x$Cocci are spherical bacteria and may occur in pairs as diplococci, chains as streptococci, or clusters as staphylococci. Bacilli are rod-shaped, vibrios are comma-shaped, and spirilla are rigid spiral-shaped organisms.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (25, $x$After Gram staining, Gram-positive bacteria appear which colour under the microscope?$x$, $x$["Pink or red","Colourless","Green","Purple or violet"]$x$, 3, $x$Gram-positive bacteria have a thick peptidoglycan cell wall that retains the crystal violet-iodine complex, so they appear purple or violet. Gram-negative bacteria lose this stain, take up the safranin counterstain, and appear pink or red.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (26, $x$Which class of immunoglobulin can cross the human placenta to provide passive immunity to the fetus?$x$, $x$["IgA","IgM","IgE","IgG"]$x$, 3, $x$IgG is the only immunoglobulin that crosses the placenta, conferring natural passive immunity on the newborn. IgM is the largest antibody and the first produced in infection, while secretory IgA predominates in breast milk and mucosal secretions.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (27, $x$Which route of drug administration provides 100 per cent bioavailability and the most rapid onset of action?$x$, $x$["Oral","Intramuscular","Subcutaneous","Intravenous"]$x$, 3, $x$Intravenous administration delivers the drug directly into the bloodstream, giving complete bioavailability and the fastest onset because it bypasses absorption and first-pass metabolism. Oral drugs are subject to incomplete absorption and hepatic first-pass effect.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (28, $x$A drug that binds to a receptor and activates it to produce a biological response is called a/an$x$, $x$["Placebo","Enzyme inhibitor","Antagonist","Agonist"]$x$, 3, $x$An agonist binds to a receptor and activates it to produce an effect, mimicking the endogenous ligand. An antagonist binds but causes no activation and blocks agonist action, whereas a placebo contains no active pharmacological ingredient.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (29, $x$Propranolol is the prototype drug of which pharmacological class?$x$, $x$["ACE inhibitor","Calcium channel blocker","Diuretic","Beta-adrenergic blocker"]$x$, 3, $x$Propranolol is a non-selective beta-adrenergic receptor blocker used in hypertension, angina and arrhythmias. It antagonises catecholamine action at beta-1 and beta-2 receptors, reducing heart rate and myocardial contractility.$x$, $x$Basic Sciences$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 15-community-env-occ.txt — 30 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-community-a — ingested draft, verify before trusting$x$, $x$Community Health Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The most effective health education approach for changing the behaviour of an individual is$x$, $x$["Mass approach","Poster campaign","Group approach","Individual approach"]$x$, 3, $x$The individual or personal contact approach is most effective for behaviour change because it allows two-way discussion of personal problems and doubts. The mass approach reaches large numbers quickly but is least effective for changing individual behaviour.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (1, $x$Which one of the following is a purely auditory aid used in health education?$x$, $x$["Flash card","Radio","Poster","Flannelgraph"]$x$, 1, $x$Radio, tape recorder and microphone are audio aids that appeal only to the sense of hearing. Poster, flannelgraph and flash card are non-projected visual aids that appeal to the sense of sight.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (2, $x$Retention of learning in health education is maximum when the method used is$x$, $x$["Learning by doing with active participation","Viewing a poster","Reading a printed pamphlet","A lecture that is only heard"]$x$, 0, $x$According to Dale's cone of experience, active participation or learning by doing gives the greatest retention of learning. Passive methods such as hearing a lecture or reading a pamphlet produce much lower retention.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (3, $x$Silicosis is an occupational lung disease caused by inhalation of dust containing$x$, $x$["Cotton dust","Coal dust","Asbestos fibres","Free silica or silicon dioxide"]$x$, 3, $x$Silicosis is caused by inhalation of free silica, affecting workers in mining, quarrying, sandblasting and pottery. Asbestos causes asbestosis, cotton dust causes byssinosis and coal dust causes anthracosis.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (4, $x$Byssinosis is an occupational disease associated with exposure to$x$, $x$["Lead fumes","Asbestos fibres","Cotton or flax dust","Silica dust"]$x$, 2, $x$Byssinosis, or Monday fever, occurs in textile workers exposed to cotton, flax or hemp dust, with chest tightness typically felt on the first working day after a break. Silica causes silicosis and asbestos causes asbestosis, not byssinosis.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (5, $x$Which malignancy is characteristically associated with occupational exposure to asbestos?$x$, $x$["Mesothelioma","Wilms tumour","Osteosarcoma","Retinoblastoma"]$x$, 0, $x$Asbestos exposure characteristically causes mesothelioma of the pleura or peritoneum, as well as bronchogenic carcinoma. Osteosarcoma, retinoblastoma and Wilms tumour have no established link with asbestos.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (6, $x$A characteristic early sign of chronic lead poisoning in adults is$x$, $x$["Koplik's spots on the buccal mucosa","Bitot's spots on the conjunctiva","A blue line on the gum margin, Burton's line","Hutchinson's teeth"]$x$, 2, $x$A blue-black lead line, Burton's line, at the gum margin is characteristic of chronic lead poisoning, along with anaemia, abdominal colic, basophilic stippling and wrist drop. Koplik's spots occur in measles and Bitot's spots in vitamin A deficiency.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (7, $x$The Employees State Insurance Act of 1948 provides all of the following benefits to insured workers except$x$, $x$["Maternity benefit","Sickness benefit","Disablement benefit","Old age pension"]$x$, 3, $x$The ESI scheme provides medical, sickness, maternity, disablement, dependant's and funeral benefits. Old-age pension is not an ESI benefit; retirement provision is covered under separate schemes such as the Employees Provident Fund.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (8, $x$Noise-induced occupational hearing loss characteristically produces its earliest audiometric dip at a frequency of$x$, $x$["500 Hz","1000 Hz","4000 Hz","8000 Hz"]$x$, 2, $x$The earliest and most characteristic change in noise-induced hearing loss is a dip in the audiogram at 4000 Hz, the acoustic notch, which appears before the speech frequencies are affected. This precedes clinically obvious deafness and is useful for early detection.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (9, $x$The committee that reviewed school health services in India in 1960 to 1961 was headed by$x$, $x$["Dr M S Chadah","Shrimati Renuka Ray","Dr A L Mudaliar","Sir Joseph Bhore"]$x$, 1, $x$The School Health Committee of 1960 to 1961 was chaired by Shrimati Renuka Ray and assessed the health and nutrition of school children in India. Bhore, Mudaliar and Chadah chaired other well-known health committees.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (10, $x$The recommended minimum floor space per pupil in a school classroom by Indian standards is approximately$x$, $x$["4 square feet","6 square feet","10 square feet","20 square feet"]$x$, 2, $x$Standards recommend about 10 square feet, roughly one square metre, of floor space per pupil, with not more than about 40 pupils per class, to prevent overcrowding. Adequate space also improves ventilation and reduces cross-infection.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (11, $x$The primary objective of the mid-day meal programme in schools is to$x$, $x$["Improve nutritional status and school attendance","Reduce school fees","Provide employment to cooks","Reduce the teacher's workload"]$x$, 0, $x$The mid-day meal programme aims to improve the nutritional status of children and to increase enrolment, retention and attendance while reducing classroom hunger. It supplies a defined share of the daily calorie and protein requirement.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (12, $x$In demography, an elderly or aged person in India is generally defined as one who has attained the age of$x$, $x$["45 years","50 years","55 years","60 years"]$x$, 3, $x$In India a person aged 60 years and above is considered elderly or a senior citizen. The rising proportion of the elderly increases the community burden of chronic and degenerative diseases.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (13, $x$The National Programme for the Health Care of the Elderly in India was launched in the year$x$, $x$["1995","1982","2010 to 2011","2017"]$x$, 2, $x$The National Programme for the Health Care of the Elderly was launched in 2010 to 2011 to provide dedicated, accessible and affordable healthcare services to the elderly at various levels of the health system. It emphasises preventive, curative and rehabilitative geriatric care.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (14, $x$The commonest cause of accidental injury among the elderly in the community, requiring preventive attention, is$x$, $x$["Drowning","Poisoning","Burns","Falls"]$x$, 3, $x$Falls are the most common cause of injury in the elderly because of impaired vision, poor balance, muscle weakness and environmental hazards. Prevention includes good lighting, grab bars, non-slip floors and removal of loose rugs.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (15, $x$In mass-casualty triage using colour coding, a victim tagged RED indicates$x$, $x$["Delayed priority, can safely wait","Immediate priority, life-threatening but salvageable","Minor injuries, the walking wounded","Dead or moribund"]$x$, 1, $x$RED denotes the first or immediate priority: serious, life-threatening injuries that are salvageable with prompt treatment. YELLOW is delayed, GREEN is minor or walking wounded, and BLACK is dead or expectant.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (16, $x$In disaster triage colour coding, which colour is assigned to victims who are dead or beyond salvageable help?$x$, $x$["Yellow","Red","Green","Black"]$x$, 3, $x$BLACK tags identify the dead or those whose injuries are so severe that survival is not expected even with treatment, the expectant category. GREEN is minor injury, YELLOW is delayed and RED is immediate priority.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (17, $x$The phase of the disaster management cycle that includes activities carried out before a disaster to reduce its impact, such as building codes and early warning systems, is$x$, $x$["Response phase","Recovery phase","Rehabilitation phase","Mitigation and preparedness phase"]$x$, 3, $x$Mitigation and preparedness are pre-disaster phases aimed at reducing impact and readying the community through warning systems, drills and disaster-resistant construction. Response occurs during impact and recovery or rehabilitation afterwards.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (18, $x$In the immediate response phase after a sudden natural disaster such as an earthquake, the first priority of health management is$x$, $x$["Immunisation of the population against tetanus","Search, rescue and first aid to casualties","Mass chemoprophylaxis to prevent epidemics","Rehabilitation and rebuilding of houses"]$x$, 1, $x$The immediate priority after a disaster is search, rescue, first aid and emergency medical care of the injured. Mass immunisation and blanket chemoprophylaxis are not indicated in the acute phase, and rehabilitation belongs to a later stage.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (19, $x$A latrine is considered sanitary primarily when it$x$, $x$["Is located inside the dwelling house","Is constructed of concrete","Prevents contamination of soil and water and excludes flies","Is fitted with a water flush"]$x$, 2, $x$A sanitary latrine must dispose of excreta so that it cannot contaminate soil, water or food and is inaccessible to flies and other vectors. The construction material, indoor location and presence of a flush are not the defining criteria.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (20, $x$In a Ventilated Improved Pit latrine, the vent pipe is fitted mainly to$x$, $x$["Supply water to the pit","Support the superstructure","Increase the capacity of the pit","Control odour and trap flies"]$x$, 3, $x$The vent pipe of a VIP latrine, usually painted dark and topped with fly-proof netting, creates an air draught that removes odour and traps escaping flies, which are drawn towards the light at the screened top. This makes it superior to a simple pit latrine.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (21, $x$In a septic tank, the liquid effluent after retention is usually disposed of by$x$, $x$["A soak pit or subsurface dispersion trench","Collection in sealed drums","Spraying directly on vegetables","Direct discharge into a river"]$x$, 0, $x$The effluent leaving a septic tank is still rich in bacteria and is disposed of through a soak pit or dispersion trenches, where it percolates and is purified by the soil. Direct discharge to surface water or crops is unsafe because pathogens survive.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (22, $x$The method of solid-waste disposal in which organic matter is decomposed by microorganisms to yield manure is$x$, $x$["Incineration","Controlled tipping","Composting","Sanitary landfill"]$x$, 2, $x$Composting is a controlled aerobic decomposition of organic refuse, and sometimes night soil, by microorganisms into a humus-like manure. Incineration burns waste, while sanitary landfill and controlled tipping bury it in the earth.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (23, $x$Waste water from kitchens, bathrooms and washing that does not contain human excreta is termed$x$, $x$["Sullage","Effluent","Sewage","Sludge"]$x$, 0, $x$Sullage is waste water from kitchen, bathroom and washing that is free of human faecal matter, whereas sewage contains human excreta. Sludge is the semi-solid residue produced during sewage treatment.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (24, $x$The classic London smog disaster of 1952, which caused thousands of deaths, was mainly due to high atmospheric levels of$x$, $x$["Ozone and nitrogen dioxide","Methane and ammonia","Carbon monoxide and lead","Sulphur dioxide and smoke particulates"]$x$, 3, $x$The 1952 London smog was a reducing or sulphurous smog caused by high levels of sulphur dioxide and smoke from coal burning under a temperature inversion. Photochemical or Los Angeles type smog, in contrast, involves ozone and oxides of nitrogen.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (25, $x$The air pollutant that has a high affinity for haemoglobin and causes tissue hypoxia by forming carboxyhaemoglobin is$x$, $x$["Sulphur dioxide","Ozone","Nitrogen dioxide","Carbon monoxide"]$x$, 3, $x$Carbon monoxide, produced by incomplete combustion in vehicle exhaust and tobacco smoke, binds haemoglobin far more strongly than oxygen, forming carboxyhaemoglobin and causing tissue hypoxia. Sulphur dioxide and ozone act mainly as respiratory irritants.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (26, $x$Prolonged occupational or community exposure to noise above which of the following levels is generally regarded as hazardous to hearing?$x$, $x$["85 to 90 dB","150 dB","45 dB","30 dB"]$x$, 0, $x$Continuous exposure above about 85 to 90 dB over an eight-hour day can cause noise-induced hearing loss, and 85 dB is taken as the safe limit. Very high levels such as 150 dB cause instantaneous damage, but everyday hazardous exposure begins near 85 to 90 dB.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (27, $x$According to the accepted overcrowding standard based on floor space, a room with 110 square feet or more of floor area should not be occupied by more than$x$, $x$["1 person","2 persons","4 persons","6 persons"]$x$, 1, $x$The standard permits 2 persons in a room of 110 square feet or more, 1.5 persons for 90 to 110 square feet and 1 person for 70 to 90 square feet. An infant under one year is not counted, and a child aged one to ten years is counted as half a person.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (28, $x$The type of ventilation that uses natural forces such as wind and temperature difference without any mechanical device is called$x$, $x$["Mechanical or artificial ventilation","Air conditioning","Exhaust ventilation","Natural ventilation"]$x$, 3, $x$Natural ventilation relies on wind pressure, temperature-difference-induced convection or stack effect and diffusion to change indoor air without machinery. Mechanical, exhaust and air-conditioning systems all require powered devices to move air.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (29, $x$In modern sewage treatment, the activated sludge process is a form of$x$, $x$["Preliminary screening","Tertiary chemical disinfection","Primary or physical treatment","Secondary or biological treatment"]$x$, 3, $x$The activated sludge process is a secondary or biological treatment in which aerobic microorganisms oxidise dissolved organic matter in aerated tanks. Primary treatment is physical sedimentation, while final disinfection such as chlorination is a later step.$x$, $x$Community Health Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 16-community-disease-prog.txt — 30 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-community-b — ingested draft, verify before trusting$x$, $x$Community Health Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The primary vector responsible for rural malaria transmission in India is which mosquito species?$x$, $x$["Phlebotomus argentipes","Anopheles culicifacies","Aedes aegypti","Culex quinquefasciatus"]$x$, 1, $x$Anopheles culicifacies is the principal vector of rural malaria in India, breeding in clean stagnant water. Culex transmits filariasis, Aedes transmits dengue and chikungunya, and Phlebotomus the sandfly transmits kala-azar.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (1, $x$Kala-azar or visceral leishmaniasis under the NVBDCP is transmitted by the bite of which vector?$x$, $x$["Phlebotomus argentipes, the sandfly","Aedes mosquito","Anopheles mosquito","Culex mosquito"]$x$, 0, $x$Kala-azar is transmitted by the female sandfly Phlebotomus argentipes, which breeds in cracks and crevices with high humidity. Man is the only reservoir in Indian kala-azar, making it a target for elimination.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (2, $x$The overwhelming majority of lymphatic filariasis cases in India are caused by which parasite?$x$, $x$["Onchocerca volvulus","Brugia malayi","Wuchereria bancrofti","Brugia timori"]$x$, 2, $x$About 99 per cent of the filariasis burden in India is due to Wuchereria bancrofti, transmitted by Culex quinquefasciatus. Mass drug administration with DEC plus albendazole is the control strategy.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (3, $x$In the epidemiology of Japanese encephalitis, the pig acts as the$x$, $x$["Definitive host","Mechanical vector","Amplifier host","Dead-end host"]$x$, 2, $x$Pigs are the main amplifier host of Japanese encephalitis, developing high viraemia without illness and multiplying the virus for onward Culex transmission. Man is only a dead-end incidental host.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (4, $x$The causative organism of leprosy is$x$, $x$["Mycobacterium avium","Mycobacterium leprae","Mycobacterium bovis","Mycobacterium tuberculosis"]$x$, 1, $x$Leprosy is caused by Mycobacterium leprae, an acid-fast bacillus with a very long generation time and a predilection for skin and peripheral nerves. The NLEP treats it with multidrug therapy.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (5, $x$Under the National Leprosy Eradication Programme, the standard duration of multidrug therapy for multibacillary leprosy is$x$, $x$["9 months","12 months","24 months","6 months"]$x$, 1, $x$Multibacillary leprosy is treated with rifampicin, clofazimine and dapsone for 12 months, while paucibacillary disease needs only 6 months. Multidrug therapy rapidly renders patients non-infectious and prevents disability.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (6, $x$The commonest cause of blindness in India, targeted under the National Programme for Control of Blindness, is$x$, $x$["Trachoma","Refractive errors","Cataract","Glaucoma"]$x$, 2, $x$Cataract accounts for roughly two thirds of blindness in India and is the leading avoidable cause. The programme emphasises high-volume cataract surgery with intraocular lens implantation to clear the backlog.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (7, $x$The National Mental Health Programme in India was launched in which year?$x$, $x$["1975","1982","1985","1992"]$x$, 1, $x$The National Mental Health Programme was launched in 1982 to ensure the availability of minimum mental healthcare and to integrate it into general health services. The District Mental Health Programme was added in 1996.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (8, $x$NPCDCS is a national programme for the prevention and control of$x$, $x$["Nutritional deficiency disorders","Communicable diseases only","Cancer, diabetes, cardiovascular diseases and stroke","Maternal and child health disorders"]$x$, 2, $x$NPCDCS stands for the National Programme for Prevention and Control of Cancer, Diabetes, Cardiovascular Diseases and Stroke. It addresses the rising burden of non-communicable disease through screening, early diagnosis and health promotion.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (9, $x$In the RMNCH+A strategy, the additional plus A component refers to$x$, $x$["Anaemia control","Antenatal care","Aged or geriatric care","Adolescent health"]$x$, 3, $x$RMNCH+A stands for Reproductive, Maternal, Newborn, Child and Adolescent Health. Adding adolescents recognised this age group as a critical link in breaking the intergenerational cycle of ill health.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (10, $x$The principal objective of Mission Indradhanush is to$x$, $x$["Reduce iron-deficiency anaemia","Control avoidable blindness","Achieve full immunisation of children and pregnant women","Eradicate malaria from endemic districts"]$x$, 2, $x$Mission Indradhanush, launched in 2014, aims to rapidly raise full immunisation coverage to at least 90 per cent by reaching unimmunised and partially immunised children and pregnant women.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (11, $x$The National AIDS Control Programme, under which NACO functions, was launched in which year?$x$, $x$["1982","1985","1987","1992"]$x$, 3, $x$The National AIDS Control Programme was launched in 1992, and NACO was established the same year to coordinate India's HIV response. It runs surveillance, blood safety, condom promotion and antiretroviral treatment services.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (12, $x$In India, a population census is conducted at intervals of every$x$, $x$["5 years","10 years","15 years","20 years"]$x$, 1, $x$The Indian census is a decennial, every ten years, complete enumeration of the population and is the oldest single source of demographic data. It provides denominators for calculating vital and health rates.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (13, $x$The Sample Registration System in India obtains reliable birth and death rates using which method?$x$, $x$["Single continuous enumeration","Decennial census enumeration","Dual record system","Hospital record compilation"]$x$, 2, $x$The SRS uses a dual record system: continuous enumeration by a resident part-time enumerator plus an independent half-yearly retrospective survey. Matching the two lists and verifying discrepancies yields dependable vital rates.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (14, $x$Registration of births and deaths was made compulsory throughout India under an Act passed in the year$x$, $x$["1948","1955","1969","1971"]$x$, 2, $x$The Registration of Births and Deaths Act of 1969 made civil registration compulsory across India. Despite this, registration completeness remains incomplete in many states, limiting the civil registration system as a source of vital statistics.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (15, $x$The usual incubation period of typhoid fever is$x$, $x$["1 to 3 days","3 to 4 weeks","5 to 7 days","10 to 14 days"]$x$, 3, $x$Typhoid fever, caused by Salmonella typhi, has an incubation period of usually 10 to 14 days depending on the infecting dose. Transmission is faeco-oral through contaminated water and food.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (16, $x$The incubation period of cholera is characteristically$x$, $x$["2 to 6 weeks","10 to 14 days","15 to 45 days","A few hours to 5 days"]$x$, 3, $x$Cholera has a very short incubation period ranging from a few hours to five days, usually one to two days. This short interval explains the explosive nature of waterborne cholera outbreaks caused by Vibrio cholerae.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (17, $x$Hepatitis A is transmitted mainly by which route?$x$, $x$["Parenteral or blood transfusion","Faeco-oral","Sexual contact","Perinatal, mother to child"]$x$, 1, $x$Hepatitis A virus spreads by the faeco-oral route through contaminated food and water and is common where sanitation is poor. It causes a self-limiting illness and does not lead to a chronic carrier state.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (18, $x$Which type of viral hepatitis carries the highest mortality when it occurs in pregnant women?$x$, $x$["Hepatitis B","Hepatitis A","Hepatitis C","Hepatitis E"]$x$, 3, $x$Hepatitis E, transmitted by the faeco-oral route, causes especially severe disease in pregnancy with fulminant hepatic failure and high case fatality, particularly in the third trimester. It is a major cause of water-borne epidemic hepatitis in India.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (19, $x$According to WHO categories of rabies exposure, a category III exposure includes$x$, $x$["Touching or feeding the animal","Minor scratches without bleeding","Nibbling of uncovered skin without a break","Transdermal bites or scratches, or contamination of a mucous membrane with saliva"]$x$, 3, $x$Category III exposures include single or multiple transdermal bites or scratches, licks on broken skin, and contamination of mucous membranes with saliva. These require immediate wound care, rabies immunoglobulin and a full anti-rabies vaccine course.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (20, $x$The single most important first-aid measure immediately after an animal bite to prevent rabies is$x$, $x$["Suture the wound immediately","Apply turmeric, lime or other irritants","Cover the wound tightly with a bandage","Wash the wound with soap and running water for about 15 minutes"]$x$, 3, $x$Prompt thorough washing of the wound with soap and plenty of running water for around 15 minutes physically removes and inactivates much of the virus. Suturing should be avoided or delayed, and irritant applications are harmful.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (21, $x$Tetanus is caused by which organism?$x$, $x$["Corynebacterium diphtheriae","Clostridium perfringens","Clostridium tetani","Clostridium botulinum"]$x$, 2, $x$Tetanus is caused by Clostridium tetani, whose spores enter through wounds and produce the neurotoxin tetanospasmin causing muscle rigidity and spasms. It is preventable by tetanus toxoid immunisation and proper wound care.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (22, $x$India was certified polio-free by the WHO in which year?$x$, $x$["2011","2012","2014","2016"]$x$, 2, $x$India recorded its last wild poliovirus case in January 2011 and, after three years without transmission, the WHO South-East Asia Region including India was certified polio-free in March 2014. Pulse polio immunisation with OPV was central to this.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (23, $x$The vector responsible for transmission of plague from rodents to humans is the$x$, $x$["Sandfly","Hard tick","Rat flea, Xenopsylla cheopis","Body louse"]$x$, 2, $x$Bubonic plague, caused by Yersinia pestis, is transmitted by the bite of the infected rat flea Xenopsylla cheopis. A blocked flea regurgitates bacilli into the bite wound, while pneumonic plague spreads directly by droplets between humans.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (24, $x$Human brucellosis is most commonly acquired through$x$, $x$["Ingestion of unpasteurised milk or contact with infected animals","Airborne droplets only","Bite of an infected mosquito","Sexual transmission"]$x$, 0, $x$Brucellosis is a zoonosis acquired mainly by consuming raw milk or milk products and through occupational contact with infected cattle, sheep and goats. Pasteurisation of milk and animal vaccination are key preventive measures.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (25, $x$Leptospirosis is transmitted to humans chiefly through$x$, $x$["Sexual contact","Inhalation of respiratory droplets","Contact with water or soil contaminated by infected animal urine","Bite of an infected mosquito"]$x$, 2, $x$Leptospirosis spreads when skin abrasions or mucous membranes contact water, mud or soil contaminated with the urine of infected animals, especially rodents. It is an occupational hazard for farmers and sewer workers and can cause Weil's disease.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (26, $x$The characteristic incubation period of staphylococcal food poisoning is$x$, $x$["1 to 6 hours","3 to 5 days","12 to 24 hours","24 to 48 hours"]$x$, 0, $x$Staphylococcal food poisoning has a very short incubation of one to six hours because it is caused by a preformed heat-stable enterotoxin rather than active infection. Vomiting predominates and recovery is usually rapid.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (27, $x$The toxin of Clostridium botulinum produces paralysis by acting at the$x$, $x$["Neuromuscular junction, blocking acetylcholine release","Renal tubules","Intestinal mucosa","Liver cells"]$x$, 0, $x$Botulinum toxin blocks the release of acetylcholine at the neuromuscular junction, producing descending flaccid paralysis, diplopia, dysphagia and respiratory failure. It is often linked to improperly preserved or canned foods.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (28, $x$The usual incubation period of non-typhoidal Salmonella food poisoning is$x$, $x$["Less than 1 hour","12 to 24 hours","1 to 6 hours","5 to 7 days"]$x$, 1, $x$Salmonella food poisoning is an infection-type illness with an incubation of about 12 to 24 hours, presenting with fever, diarrhoea and abdominal cramps. It is commonly linked to poultry, eggs and inadequately cooked meat.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (29, $x$Under the National Vitamin A Prophylaxis Programme, the first dose of vitamin A is given as$x$, $x$["200000 IU at 9 months of age","100000 IU at 9 months of age","200000 IU at 12 months of age","100000 IU at 6 months of age"]$x$, 1, $x$The first dose of vitamin A is 100000 IU given at 9 months along with measles vaccine. Subsequent doses of 200000 IU are given every six months up to five years of age to prevent nutritional blindness.$x$, $x$Community Health Nursing$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 17-medsurg-cardio-renal.txt — 30 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-medsurg-a — ingested draft, verify before trusting$x$, $x$Medical-Surgical Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$Which feature is most characteristic of stable angina pectoris?$x$, $x$["Chest pain precipitated by exertion and relieved within minutes by rest or sublingual nitroglycerin","Crushing chest pain lasting more than 30 minutes and unrelieved by rest","Chest pain occurring only during sleep with persistent ST-segment elevation","Continuous chest pain that worsens progressively over several days"]$x$, 0, $x$Stable angina is predictable, provoked by increased myocardial oxygen demand such as exertion, and typically subsides within a few minutes with rest or nitroglycerin. Pain lasting beyond 20 to 30 minutes suggests myocardial infarction rather than stable angina.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (1, $x$How does unstable angina differ from stable angina?$x$, $x$["It occurs at rest or has a new onset, increasing in frequency, duration or severity","It follows a fixed, predictable pattern brought on only by heavy exertion","It is always fully relieved within two minutes of taking nitroglycerin","It never requires hospitalisation or cardiac monitoring"]$x$, 0, $x$Unstable angina is part of acute coronary syndrome and occurs at rest, is of new onset, or shows a crescendo pattern of increasing frequency and severity. It signals an unstable atherosclerotic plaque and warrants urgent evaluation and continuous monitoring.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (2, $x$In the first few hours following an acute myocardial infarction, the most common cause of death is$x$, $x$["Dressler syndrome","Ventricular fibrillation and other lethal dysrhythmias","Ventricular aneurysm formation","Slowly progressive chronic heart failure"]$x$, 1, $x$Lethal ventricular dysrhythmias, especially ventricular fibrillation, are the leading cause of death in the early hours after myocardial infarction. This is why continuous cardiac monitoring and immediate defibrillation capability are essential during this period.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (3, $x$During phase I inpatient cardiac rehabilitation after myocardial infarction, appropriate nursing guidance is to$x$, $x$["Enforce strict, complete bed rest until the day of discharge","Progress gradually with low-level activities such as self-care and short supervised walks","Prohibit all self-care activities to conserve myocardial oxygen","Begin high-intensity aerobic training on the first day"]$x$, 1, $x$Phase I rehabilitation emphasises gradual, low-level activity such as self-care, sitting up, and short monitored walks while observing the patient's tolerance. Activity is advanced slowly based on the absence of symptoms, dysrhythmias and abnormal vital sign responses.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (4, $x$ACE inhibitors improve survival in chronic heart failure mainly by$x$, $x$["Directly increasing the heart rate and contractility","Promoting sodium and water retention to raise preload","Reducing afterload and preventing maladaptive ventricular remodeling","Increasing systemic vascular resistance and afterload"]$x$, 2, $x$ACE inhibitors block the renin-angiotensin-aldosterone system, producing vasodilation that lowers afterload and reducing angiotensin II-driven ventricular remodeling. These effects decrease cardiac workload and improve long-term survival in heart failure.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (5, $x$Primary or essential hypertension is best defined as elevated blood pressure that$x$, $x$["Is confined to the paediatric population","Results from an identifiable cause such as renal artery stenosis or phaeochromocytoma","Has no single identifiable underlying cause and accounts for most cases","Occurs only transiently during an acute illness"]$x$, 2, $x$Primary or essential hypertension has no identifiable secondary cause and represents roughly 90 to 95 per cent of all hypertension cases. Secondary hypertension, by contrast, results from a specific identifiable condition such as renal or endocrine disease.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (6, $x$When managing a hypertensive emergency, the recommended goal for initial blood pressure reduction is to$x$, $x$["Lower the mean arterial pressure by no more than about 20 to 25 per cent in the first hour","Reduce the systolic pressure below 90 mmHg as quickly as possible","Avoid any reduction until end-organ damage is confirmed","Lower the blood pressure to completely normal values within 15 minutes"]$x$, 0, $x$In a hypertensive emergency the mean arterial pressure should be lowered gradually, by roughly 20 to 25 per cent within the first hour, then further over the following hours. Overly rapid reduction can precipitate cerebral, coronary or renal ischaemia due to impaired autoregulation.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (7, $x$Which auscultatory finding is classic for mitral stenosis?$x$, $x$["A harsh crescendo-decrescendo systolic ejection murmur at the aortic area","A high-pitched blowing pansystolic murmur radiating to the axilla","A low-pitched rumbling mid-diastolic murmur at the apex, often with an opening snap","A continuous machinery-like murmur below the left clavicle"]$x$, 2, $x$Mitral stenosis produces a low-pitched, rumbling mid-diastolic murmur best heard at the apex, frequently preceded by an opening snap. A pansystolic murmur radiating to the axilla instead points to mitral regurgitation.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (8, $x$A patient discharged with a newly implanted permanent pacemaker should be taught to$x$, $x$["Report dizziness, prolonged hiccups, or a pulse rate below the pacemaker's set rate","Avoid taking the pulse so as not to cause unnecessary anxiety","Undergo any MRI scan freely without informing staff about the device","Stop all physical activity permanently to protect the device"]$x$, 0, $x$Patients should check their pulse daily and report dizziness, syncope, persistent hiccups which may indicate lead-related diaphragmatic stimulation, or a rate below the set pacemaker rate. These may signal pacemaker malfunction requiring prompt evaluation.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (9, $x$According to current basic life support guidelines, the recommended rate of chest compressions for an adult is$x$, $x$["40 to 60 compressions per minute","140 to 160 compressions per minute","100 to 120 compressions per minute","60 to 80 compressions per minute"]$x$, 2, $x$High-quality CPR requires a compression rate of 100 to 120 per minute for adults. Rates that are too slow or too fast reduce the effectiveness of the circulation generated during resuscitation.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (10, $x$Cardiogenic shock is most accurately described as$x$, $x$["Hypovolaemia due to acute blood or fluid loss","Widespread vasodilation and maldistribution of blood flow from sepsis","A high-output state with warm, well-perfused extremities","Decreased cardiac output and tissue hypoperfusion despite adequate intravascular volume"]$x$, 3, $x$Cardiogenic shock results from failure of the heart to pump effectively, producing decreased cardiac output and tissue hypoperfusion even though circulating blood volume is adequate. It most often follows extensive myocardial infarction with significant left ventricular damage.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (11, $x$The hallmark clinical sign of acute pericarditis is$x$, $x$["A fixed, widely split second heart sound","Muffled heart sounds with an otherwise silent precordium","Bilateral coarse crackles throughout both lung fields","A pericardial friction rub on auscultation"]$x$, 3, $x$A pericardial friction rub, a scratchy or grating sound, is the classic auscultatory finding in acute pericarditis. The associated chest pain is typically sharp and pleuritic, worsens when lying supine, and eases when the patient sits up and leans forward.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (12, $x$Which nursing intervention is appropriate during the acute phase of deep vein thrombosis of the leg?$x$, $x$["Vigorously massage the calf to improve venous return","Elevate the affected limb and administer anticoagulant therapy as prescribed","Keep the affected leg dependent and encourage brisk walking","Apply firm heat and have the patient perform forceful leg exercises"]$x$, 1, $x$During acute DVT the affected extremity is elevated to reduce oedema and anticoagulation is given to prevent clot extension and embolisation. Massaging the calf is contraindicated because it can dislodge the thrombus and cause pulmonary embolism.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (13, $x$In acute pulmonary embolism, the typical early arterial blood gas pattern is$x$, $x$["Metabolic acidosis with a normal PaO2","Metabolic alkalosis with hypoventilation","Hypoxaemia with respiratory alkalosis due to hyperventilation","Respiratory acidosis with a high PaCO2"]$x$, 2, $x$Pulmonary embolism causes hypoxaemia, and the resulting tachypnoea and hyperventilation blow off carbon dioxide, lowering the PaCO2 and producing respiratory alkalosis. This combination of hypoxaemia with respiratory alkalosis is the classic early blood gas picture.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (14, $x$The correct isolation precaution for a patient with active pulmonary tuberculosis is$x$, $x$["Contact precautions with gown and gloves only","Airborne precautions in a negative-pressure room with a fitted N95 respirator","Droplet precautions with a surgical mask only","Standard precautions alone are sufficient"]$x$, 1, $x$Mycobacterium tuberculosis spreads via droplet nuclei that remain suspended in the air, so airborne precautions are required. The patient is placed in a negative-pressure room and staff wear a fit-tested N95 respirator when entering.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (15, $x$Hospital-acquired or nosocomial pneumonia is defined as pneumonia that develops$x$, $x$["Exclusively outside of any healthcare facility","Within the first 12 hours of hospital admission","Only in patients who are immunosuppressed","48 hours or more after admission and was not incubating at the time of admission"]$x$, 3, $x$Hospital-acquired pneumonia is diagnosed when pneumonia appears 48 hours or more after admission and was not present or incubating on arrival. It is frequently caused by more resistant organisms than community-acquired pneumonia.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (16, $x$A hallmark feature of acute respiratory distress syndrome is$x$, $x$["A slowly progressive course developing over many years","High lung compliance that makes ventilation easy","Severe refractory hypoxaemia that does not improve with supplemental oxygen","Hypoxaemia that corrects readily with low-flow nasal oxygen"]$x$, 2, $x$ARDS is characterised by refractory hypoxaemia caused by non-cardiogenic pulmonary oedema, alveolar collapse and impaired gas exchange that does not respond to increasing oxygen. It presents with bilateral infiltrates and markedly reduced lung compliance requiring ventilatory support.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (17, $x$Immediately following a thoracentesis for pleural effusion, the priority nursing assessment is to$x$, $x$["Encourage the patient to cough as forcefully as possible","Keep the patient lying completely flat and immobile for 24 hours","Monitor for signs of pneumothorax such as sudden dyspnoea and decreased breath sounds","Withhold vital sign monitoring to allow the patient to rest"]$x$, 2, $x$Pneumothorax is a key complication of thoracentesis because the needle may inadvertently puncture the lung. The nurse watches for sudden dyspnoea, decreased or absent breath sounds, and tachycardia, and a post-procedure chest x-ray is obtained as ordered.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (18, $x$A characteristic clinical feature of bronchiectasis is$x$, $x$["A brief dry cough with no sputum production","Complete absence of respiratory symptoms between infections","Chronic cough producing copious amounts of purulent, often foul-smelling sputum","Sudden pleuritic chest pain with no cough"]$x$, 2, $x$Bronchiectasis involves permanent abnormal dilation of the bronchi with impaired mucus clearance, leading to a chronic cough that produces large volumes of purulent, frequently foul-smelling sputum. Recurrent respiratory infections and haemoptysis are also common.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (19, $x$The nasal cannula is best described as an oxygen delivery device that$x$, $x$["Is a high-flow system that fully meets the patient's entire inspiratory demand","Is a low-flow device delivering roughly 24 to 44 per cent oxygen at 1 to 6 L/min","Can safely deliver 100 per cent oxygen at 15 L/min","Delivers a precise, fixed fraction of inspired oxygen regardless of breathing pattern"]$x$, 1, $x$The nasal cannula is a low-flow device that delivers approximately 24 to 44 per cent oxygen at flow rates of 1 to 6 litres per minute. The actual inspired concentration varies with the patient's respiratory rate and tidal volume.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (20, $x$During the oliguric phase of acute kidney injury, the nurse should monitor most closely for$x$, $x$["Hypernatraemia with rapid weight loss","Hypokalaemia and profound dehydration","Metabolic alkalosis with a low potassium level","Hyperkalaemia and fluid volume overload"]$x$, 3, $x$In the oliguric phase of acute kidney injury, reduced urine output causes retention of fluid, potassium and metabolic acids, producing fluid overload, hyperkalaemia and metabolic acidosis. Hyperkalaemia is especially dangerous because of its risk of fatal cardiac dysrhythmias.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (21, $x$The most common complication of peritoneal dialysis is$x$, $x$["Haemolysis of red blood cells","Peritonitis","Air embolism","Dialysis disequilibrium syndrome"]$x$, 1, $x$Peritonitis is the most common and serious complication of peritoneal dialysis, usually resulting from contamination during exchanges. Cloudy dialysate outflow is often the earliest sign, and strict aseptic technique is essential to prevent it.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (22, $x$A patient with an acute renal calculus reports severe colicky flank pain. The priority nursing actions are to$x$, $x$["Provide prescribed analgesia and strain all urine to detect passage of the stone","Restrict fluid intake to reduce urine formation","Enforce strict bed rest and avoid all movement","Withhold analgesia until the stone has passed spontaneously"]$x$, 0, $x$Renal colic is intensely painful, so prompt administration of prescribed analgesia is a priority, along with straining all urine to catch the stone for laboratory analysis. Adequate fluid intake and ambulation are also encouraged to help promote stone passage.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (23, $x$Benign prostatic hyperplasia most commonly presents with$x$, $x$["Sudden severe flank pain radiating to the groin","Lower urinary tract symptoms such as hesitancy, weak stream, frequency and nocturia","Complete and permanent absence of any urinary symptoms","Painless gross haematuria as the only symptom"]$x$, 1, $x$Benign prostatic hyperplasia enlarges the prostate and obstructs the bladder outlet, producing lower urinary tract symptoms including hesitancy, a weak urinary stream, frequency, urgency and nocturia. Untreated obstruction can progress to urinary retention and recurrent infection.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (24, $x$To reduce the risk of catheter-associated urinary tract infection, the nurse should$x$, $x$["Place the drainage bag on the bed beside the patient during transfers","Keep the drainage bag below bladder level and maintain a closed drainage system","Routinely open the system to irrigate and check the urine flow each shift","Clamp the catheter for several hours each shift to promote bladder training"]$x$, 1, $x$Keeping the drainage bag below the level of the bladder prevents backflow of urine, and maintaining a closed drainage system limits the entry of organisms. These are core measures for preventing catheter-associated urinary tract infection.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (25, $x$Hyponatraemia is defined as a serum sodium concentration below$x$, $x$["145 mEq/L","155 mEq/L","125 mEq/L","135 mEq/L"]$x$, 3, $x$Hyponatraemia is defined as a serum sodium level below 135 mEq/L, the lower limit of the normal 135 to 145 mEq/L range. Severe or rapidly developing hyponatraemia causes cerebral oedema, producing headache, confusion and seizures.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (26, $x$Which intervention most rapidly protects the myocardium against the effects of severe hyperkalaemia?$x$, $x$["Intravenous calcium gluconate","An oral potassium-sparing diuretic","An oral potassium supplement","A slow infusion of potassium chloride"]$x$, 0, $x$Intravenous calcium gluconate is given first in severe hyperkalaemia because it stabilises the cardiac cell membrane and antagonises the effect of potassium on the heart. It does not lower serum potassium, so insulin with glucose or other measures are added to shift or remove potassium.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (27, $x$Which pair of clinical signs suggests hypocalcaemia?$x$, $x$["A positive Murphy sign and rebound tenderness","A positive Homans sign and Kernig sign","A positive Trousseau sign and Chvostek sign","A positive Cullen sign and Grey Turner sign"]$x$, 2, $x$Hypocalcaemia increases neuromuscular excitability, producing a positive Trousseau sign of carpopedal spasm when a blood pressure cuff is inflated and a positive Chvostek sign of facial twitching when the facial nerve is tapped. Severe hypocalcaemia can cause tetany, laryngospasm and seizures.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (28, $x$An arterial blood gas shows pH 7.30, PaCO2 55 mmHg, and HCO3 24 mEq/L. This indicates$x$, $x$["Metabolic alkalosis","Uncompensated metabolic acidosis","Uncompensated respiratory acidosis","Respiratory alkalosis"]$x$, 2, $x$The low pH indicates acidosis, the elevated PaCO2 identifies a respiratory cause, and the normal bicarbonate shows that no metabolic compensation has occurred. Together these values represent uncompensated respiratory acidosis, typically due to alveolar hypoventilation.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (29, $x$An arterial blood gas shows pH 7.50, HCO3 32 mEq/L, and PaCO2 40 mmHg. This indicates$x$, $x$["Respiratory acidosis","Respiratory alkalosis","Metabolic acidosis","Metabolic alkalosis"]$x$, 3, $x$The elevated pH indicates alkalosis and the raised bicarbonate identifies a metabolic origin, while the normal PaCO2 shows the lungs have not yet compensated. These findings represent an uncompensated metabolic alkalosis.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 18-medsurg-endo-neuro.txt — 30 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-medsurg-b — ingested draft, verify before trusting$x$, $x$Medical-Surgical Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$Which finding is most characteristic of hyperthyroidism (Graves' disease)?$x$, $x$["Cold, dry skin with bradycardia","Constipation and lethargy","Exophthalmos and heat intolerance","Weight gain despite poor appetite"]$x$, 2, $x$Graves' disease produces a hypermetabolic state with exophthalmos, heat intolerance, weight loss despite good appetite, tachycardia, and warm moist skin. The other options describe hypothyroidism.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (1, $x$A patient develops thyroid storm after thyroidectomy. Which finding is the hallmark of this crisis?$x$, $x$["Temperature 35 C with slow pulse","Temperature 41 C with heart rate 160/min","Serum sodium 118 mEq/L","Blood glucose 40 mg/dL"]$x$, 1, $x$Thyroid storm is a life-threatening exacerbation of hyperthyroidism marked by extreme hyperpyrexia, severe tachycardia or tachyarrhythmias, and altered mental status. It requires urgent cooling, beta-blockers, and antithyroid drugs.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (2, $x$Which set of findings would the nurse expect in a patient with myxoedema coma?$x$, $x$["Hyperglycaemia and Kussmaul respirations","Hypothermia, hyponatraemia, and depressed level of consciousness","Fever, tachycardia, and hypertension","Exophthalmos, tremor, and diarrhoea"]$x$, 1, $x$Myxoedema coma is severe decompensated hypothyroidism presenting with hypothermia, hyponatraemia, hypoventilation, bradycardia, and reduced consciousness. It is a medical emergency treated with IV thyroid hormone and supportive care.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (3, $x$Which clinical feature is most characteristic of Cushing's syndrome?$x$, $x$["Hyperpigmentation with hypotension","Weight loss and hypoglycaemia","Cold intolerance and periorbital oedema","Truncal obesity with a moon face and buffalo hump"]$x$, 3, $x$Excess cortisol in Cushing's syndrome causes central truncal obesity, moon face, buffalo hump, purple striae, hyperglycaemia, and hypertension. Hyperpigmentation with hypotension instead suggests adrenal insufficiency.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (4, $x$Which statement correctly describes type 1 diabetes mellitus?$x$, $x$["It never leads to ketoacidosis","It results from autoimmune destruction of pancreatic beta cells and requires insulin","It is typically managed with diet and oral hypoglycaemics alone","It is caused primarily by insulin resistance in obese adults"]$x$, 1, $x$Type 1 diabetes results from autoimmune destruction of insulin-producing beta cells, causing absolute insulin deficiency and lifelong insulin dependence. Type 2 is characterised by insulin resistance and relative deficiency, often in adults.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (5, $x$A patient with diabetes insipidus is most likely to show which findings?$x$, $x$["Hyponatraemia with weight gain","Concentrated urine with fluid retention","Large volumes of dilute urine with low urine specific gravity","Oliguria with high urine osmolality"]$x$, 2, $x$Diabetes insipidus results from ADH deficiency or resistance, producing polyuria of dilute urine with low specific gravity, intense thirst, and risk of hypernatraemia and dehydration. Careful fluid balance and desmopressin are key to management.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (6, $x$Which nursing intervention is appropriate for a patient with syndrome of inappropriate antidiuretic hormone (SIADH)?$x$, $x$["Administer intravenous 5% dextrose freely","Give desmopressin to reduce urine output","Restrict fluids and monitor serum sodium","Encourage a high fluid intake"]$x$, 2, $x$SIADH causes excess ADH, water retention, dilutional hyponatraemia, and concentrated urine. Management centres on fluid restriction, monitoring serum sodium, and sometimes hypertonic saline; giving free water or desmopressin would worsen it.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (7, $x$Which nursing action is most appropriate for a patient with cirrhosis and ascites?$x$, $x$["Position the patient flat to ease breathing","Measure abdominal girth and daily weight","Restrict protein completely in all patients","Encourage a high-sodium diet"]$x$, 1, $x$Monitoring abdominal girth and daily weight tracks fluid accumulation in ascites. Care includes sodium and fluid restriction, semi-Fowler's positioning to ease breathing, and diuretics; protein is moderated only if encephalopathy develops.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (8, $x$A cirrhotic patient with bleeding oesophageal varices is admitted. What is the nurse's priority?$x$, $x$["Encourage vigorous coughing","Maintain airway and manage the haemorrhage","Provide a high-fibre diet immediately","Position the patient supine and flat"]$x$, 1, $x$Ruptured oesophageal varices cause massive upper GI bleeding, so airway protection and haemodynamic support are the priority. Management includes fluid and blood replacement, vasoactive drugs like octreotide, endoscopic banding, and balloon tamponade if needed.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (9, $x$Which laboratory finding best supports a diagnosis of acute pancreatitis?$x$, $x$["Markedly elevated serum amylase and lipase","Elevated serum ammonia","Elevated serum bilirubin only","Decreased serum lipase"]$x$, 0, $x$Acute pancreatitis is confirmed by markedly raised serum amylase and, more specifically, lipase. Nursing care emphasises pain control, keeping the patient NPO to rest the pancreas, IV fluids, and monitoring for hypocalcaemia and shock.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (10, $x$Which feature distinguishes Crohn's disease from ulcerative colitis?$x$, $x$["It involves only the mucosal layer","It is limited to the rectum and colon","It causes transmural inflammation with skip lesions anywhere in the GI tract","It always spares the small intestine"]$x$, 2, $x$Crohn's disease causes transmural inflammation with discontinuous skip lesions that may involve any part of the GI tract from mouth to anus. Ulcerative colitis is continuous, mucosal, and confined to the rectum and colon.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (11, $x$Which precaution is most important when caring for a patient with hepatitis B?$x$, $x$["Wearing a mask for all contact","Strict fluid restriction","Standard precautions with careful handling of blood and body fluids","Airborne isolation in a negative-pressure room"]$x$, 2, $x$Hepatitis B is transmitted through blood and body fluids, so standard precautions with safe handling of needles and body fluids are essential. Hepatitis A and E spread by the faecal-oral route and require attention to hand hygiene and sanitation.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (12, $x$Which symptom is most characteristic of acute cholecystitis?$x$, $x$["Right upper quadrant pain after a fatty meal","Painless jaundice with weight gain","Burning epigastric pain relieved by food","Lower left quadrant pain with diarrhoea"]$x$, 0, $x$Acute cholecystitis typically causes right upper quadrant pain, often after a fatty meal, with nausea and a positive Murphy's sign. Gallstones are the usual cause, and pain may radiate to the right shoulder or scapula.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (13, $x$Which finding would the nurse expect in a patient with mechanical small bowel obstruction?$x$, $x$["Abdominal distension with vomiting and high-pitched bowel sounds","Increased frequency of normal bowel movements","Soft non-tender abdomen with normal appetite","Passage of large formed stools"]$x$, 0, $x$Mechanical bowel obstruction produces colicky pain, abdominal distension, vomiting, obstipation, and early high-pitched then later absent bowel sounds. Management includes NPO status, nasogastric decompression, and fluid and electrolyte replacement.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (14, $x$Which statement about stroke management is correct?$x$, $x$["CT scanning is unnecessary before treatment","Thrombolytic therapy is used only for ischaemic stroke within the time window","All strokes are treated with immediate anticoagulation","Haemorrhagic stroke is treated with thrombolytics"]$x$, 1, $x$Thrombolytic therapy is indicated only for ischaemic stroke within the eligible time window and after haemorrhage is excluded by CT. Giving thrombolytics in haemorrhagic stroke would be catastrophic, so imaging always precedes treatment.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (15, $x$A patient with a right-hemisphere stroke has left homonymous hemianopia. Which rehabilitation approach is appropriate?$x$, $x$["Restrict the patient to bed to prevent falls","Teach the patient to scan toward the affected side and approach from the unaffected side initially","Speak only from the affected left side","Avoid teaching because the deficit is permanent"]$x$, 1, $x$With homonymous hemianopia the patient loses half the visual field, so teaching deliberate head-scanning toward the affected side improves safety. Initially placing objects and approaching from the intact side reduces neglect-related injury.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (16, $x$Which group of signs is characteristic of Parkinson's disease?$x$, $x$["Intention tremor with scanning speech and nystagmus","Resting pill-rolling tremor, bradykinesia, rigidity, and shuffling gait","Ascending flaccid paralysis","Sudden hemiparesis and aphasia"]$x$, 1, $x$Parkinson's disease features the classic triad of resting pill-rolling tremor, bradykinesia, and cogwheel rigidity, along with a stooped posture and shuffling festinating gait. It results from dopamine depletion in the substantia nigra.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (17, $x$Which statement best describes multiple sclerosis?$x$, $x$["It is a chronic demyelinating disease with a relapsing-remitting course","It is caused by dopamine deficiency","It causes permanent flaccid paralysis within hours","It is an acute bacterial infection of the meninges"]$x$, 0, $x$Multiple sclerosis is a chronic autoimmune demyelinating disease of the central nervous system, often following a relapsing-remitting pattern. Symptoms include fatigue, visual disturbances, weakness, and impaired coordination, and heat can worsen them.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (18, $x$A patient with myasthenia gravis develops worsening weakness. Which feature suggests myasthenic crisis rather than cholinergic crisis?$x$, $x$["Excessive salivation, diarrhoea, and muscle fasciculations","Improvement of weakness after giving more anticholinesterase","Weakness that worsens because of insufficient anticholinesterase medication","Constricted pupils with abdominal cramps"]$x$, 2, $x$Myasthenic crisis is severe weakness from undermedication or a trigger, improving with anticholinesterase and needing airway support. Cholinergic crisis results from overmedication, causing muscarinic effects such as salivation, diarrhoea, and fasciculations.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (19, $x$Which assessment is the priority in a patient with Guillain-Barre syndrome?$x$, $x$["Checking pupillary size every shift","Monitoring blood glucose hourly","Monitoring respiratory function and vital capacity","Assessing for a rigid, board-like abdomen"]$x$, 2, $x$Guillain-Barre syndrome causes an ascending paralysis that can involve the respiratory muscles, so serial vital capacity and respiratory monitoring are the priority. Declining vital capacity signals impending respiratory failure requiring ventilatory support.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (20, $x$Which finding supports a diagnosis of bacterial meningitis?$x$, $x$["Flaccid ascending paralysis","Resting tremor and rigidity","Nuchal rigidity with positive Kernig's and Brudzinski's signs","Painless loss of vision"]$x$, 2, $x$Bacterial meningitis presents with fever, severe headache, photophobia, and nuchal rigidity, with positive Kernig's and Brudzinski's signs. Droplet precautions, prompt antibiotics, and neurological monitoring are essential nursing priorities.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (21, $x$Which precaution is essential when a nurse administers cytotoxic chemotherapy?$x$, $x$["Wear chemotherapy-rated gloves and gown and use a spill kit for spills","Dispose of drug waste in the regular bin","No special protective equipment is required","Recap and reuse needles to reduce waste"]$x$, 0, $x$Cytotoxic drugs are hazardous, so nurses must use chemotherapy-rated gloves and gowns, prepare drugs in a biological safety cabinet, and manage spills with a designated spill kit. Waste and sharps go into labelled cytotoxic containers.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (22, $x$Which instruction is correct for a patient receiving external beam radiation therapy?$x$, $x$["Expose the irradiated skin to direct sunlight to promote healing","Scrub the skin markings off daily","Do not wash off skin markings and avoid lotions, powders, and sun exposure to the site","Apply heating pads to the treatment site"]$x$, 2, $x$Radiation skin markings must be preserved to ensure accurate targeting, so the site is gently patted, not scrubbed. Patients should avoid lotions, powders, heat, friction, and sun exposure over the treated area to prevent skin breakdown.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (23, $x$According to the CAUTION warning signs of cancer, which of the following should prompt evaluation?$x$, $x$["Transient muscle soreness after exercise","Occasional mild tension headache","Brief seasonal sneezing","A sore that does not heal or unusual bleeding or discharge"]$x$, 3, $x$The CAUTION mnemonic highlights early cancer warning signs, including a change in bowel or bladder habits, a sore that does not heal, unusual bleeding or discharge, a lump, indigestion or dysphagia, an obvious change in a wart or mole, and a nagging cough.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (24, $x$Which is the primary goal of palliative and end-of-life care?$x$, $x$["Pursuing aggressive curative treatment at all costs","Restricting family presence during the dying process","Withholding all analgesia to preserve alertness","Providing comfort and relief of symptoms such as pain and dyspnoea"]$x$, 3, $x$Palliative care focuses on comfort and quality of life, relieving distressing symptoms such as pain, dyspnoea, and nausea rather than curing disease. It supports the patient and family holistically, including emotional and spiritual needs.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (25, $x$An incomplete fracture in which the bone bends and cracks, common in children, is called a$x$, $x$["Pathological fracture","Greenstick fracture","Compound fracture","Comminuted fracture"]$x$, 1, $x$A greenstick fracture is an incomplete break where the bone bends and cracks, typical of children whose bones are more pliable. A comminuted fracture shatters into fragments, and a compound or open fracture breaks through the skin.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (26, $x$Which nursing action is appropriate for a patient with a newly applied plaster cast?$x$, $x$["Insert a knitting needle to scratch inside the cast","Cover the wet cast with a blanket to speed drying","Rest the wet cast on a hard flat surface","Elevate the limb and perform neurovascular checks"]$x$, 3, $x$A new cast is elevated to reduce swelling, and frequent neurovascular checks of colour, warmth, pulses, capillary refill, movement, and sensation detect compromise early. The cast should dry uncovered, be handled with the palms, and nothing should be inserted inside it.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (27, $x$Which feature is more characteristic of rheumatoid arthritis than osteoarthritis?$x$, $x$["Involvement of weight-bearing joints from wear and tear","Symmetric joint involvement with morning stiffness lasting more than one hour and systemic symptoms","Heberden's nodes at the distal interphalangeal joints","Asymmetric joint involvement with brief morning stiffness"]$x$, 1, $x$Rheumatoid arthritis is a systemic autoimmune disease causing symmetric joint inflammation, prolonged morning stiffness over an hour, fatigue, and fever. Osteoarthritis is a degenerative wear-and-tear disorder with asymmetric involvement and brief stiffness.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (28, $x$Which intervention helps prevent and manage osteoporosis?$x$, $x$["Avoiding all physical activity","Strict bed rest to protect fragile bones","A high-caffeine, high-alcohol diet","Adequate calcium and vitamin D intake with weight-bearing exercise"]$x$, 3, $x$Osteoporosis is characterised by low bone density and increased fracture risk, so prevention relies on adequate calcium and vitamin D, weight-bearing exercise, and fall prevention. Smoking, excess alcohol, caffeine, and inactivity worsen bone loss.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (29, $x$Which statement about osteomyelitis is correct?$x$, $x$["It never requires surgical debridement","It is best treated with a short single dose of oral antibiotics","It is a bone infection usually requiring prolonged intravenous antibiotic therapy","It is a non-infectious degeneration of cartilage"]$x$, 2, $x$Osteomyelitis is an infection of bone, most often bacterial, presenting with pain, fever, swelling, and warmth over the site. Treatment involves prolonged intravenous antibiotics and sometimes surgical debridement of necrotic sequestrum tissue.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 19-obg-child-2.txt — 28 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$w1-obg-child — ingested draft, verify before trusting$x$, $x$Obstetrics & Child Health$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$During which phase of the endometrial cycle does progesterone from the corpus luteum convert the lining into a secretory glandular structure ready for implantation?$x$, $x$["Secretory phase","Proliferative phase","Menstrual phase","Regenerative phase"]$x$, 0, $x$After ovulation the corpus luteum secretes progesterone, which transforms the proliferative endometrium into a secretory one with tortuous glands and glycogen stores. This prepares the lining to receive the blastocyst for implantation.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (1, $x$Fertilisation of the ovum by the sperm most commonly takes place in which part of the fallopian tube?$x$, $x$["Ampulla","Isthmus","Infundibulum","Interstitial part"]$x$, 0, $x$The ampulla is the widest and longest segment of the tube, where the sperm normally meets and fertilises the ovum. The resulting zygote then travels toward the uterine cavity over the next few days for implantation.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (2, $x$Implantation of the blastocyst into the uterine endometrium normally occurs about how many days after fertilisation?$x$, $x$["1 to 2 days","14 to 15 days","10 to 11 days","6 to 7 days"]$x$, 3, $x$The blastocyst reaches the uterine cavity around day 4 to 5 and begins to implant in the secretory endometrium about 6 to 7 days after fertilisation. The process of implantation is usually completed by about day 10 to 11.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (3, $x$The physiological fall in haemoglobin concentration during pregnancy is chiefly explained by which of the following?$x$, $x$["Increased red cell destruction","A greater rise in plasma volume than in red cell mass","Reduced erythropoietin secretion","Chronic iron deficiency"]$x$, 1, $x$Plasma volume increases by about 45 to 50 per cent whereas red cell mass rises only around 20 to 30 per cent, producing a dilutional or physiological anaemia. This apparent fall in haemoglobin is maximal near 30 to 32 weeks of gestation.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (4, $x$All of the following are recognised antenatal danger signs that warrant urgent evaluation except$x$, $x$["Reduced or absent fetal movements","Severe persistent headache with blurred vision","Vaginal bleeding","Mild bilateral ankle oedema in the third trimester"]$x$, 3, $x$Mild dependent ankle oedema is a common and benign finding in late pregnancy due to venous stasis. Vaginal bleeding, severe headache with visual disturbance, and reduced fetal movements are true danger signs requiring immediate assessment.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (5, $x$Under the DIPSI single-step protocol used in India, gestational diabetes is diagnosed when the two-hour plasma glucose after a 75 gram oral glucose load is at least$x$, $x$["140 mg/dL","110 mg/dL","200 mg/dL","160 mg/dL"]$x$, 0, $x$In the DIPSI test a 75 gram glucose load is given irrespective of the last meal and plasma glucose is measured at two hours. A value of 140 mg/dL or more diagnoses gestational diabetes, making it a convenient single-step field test.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (6, $x$According to ICMR grading of anaemia in pregnancy, a haemoglobin level of 7 to 10 g/dL is classified as$x$, $x$["Mild anaemia","Moderate anaemia","Severe anaemia","Very severe anaemia"]$x$, 1, $x$ICMR grades anaemia as mild at 10 to 10.9 g/dL, moderate at 7 to 10 g/dL, severe at 4 to 6.9 g/dL and very severe below 4 g/dL. Moderate anaemia usually requires oral or, if not tolerated, parenteral iron therapy.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (7, $x$A woman with severe hyperemesis gravidarum develops confusion, nystagmus and ataxia. This complication results from deficiency of which vitamin?$x$, $x$["Vitamin D","Vitamin B1 or thiamine","Vitamin B12","Vitamin C"]$x$, 1, $x$Prolonged vomiting depletes thiamine and can precipitate Wernicke's encephalopathy, presenting with the triad of confusion, ophthalmoplegia or nystagmus, and ataxia. Thiamine must therefore be given before any glucose-containing infusion.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (8, $x$Twin-to-twin transfusion syndrome, in which one fetus becomes a donor and the other a recipient, occurs only in which type of twin pregnancy?$x$, $x$["Dizygotic","Monochorionic","Any dichorionic pregnancy","Dichorionic diamniotic"]$x$, 1, $x$This syndrome arises from placental vascular anastomoses shared by monochorionic twins who have a single placenta, causing unequal blood distribution. Dichorionic and dizygotic twins have separate placentas and are not affected.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (9, $x$Polyhydramnios is diagnosed when the total liquor volume exceeds approximately$x$, $x$["500 mL","1000 mL","1500 mL","2000 mL"]$x$, 3, $x$Normal amniotic fluid at term is about 500 to 1500 mL; polyhydramnios is defined as more than 2000 mL or an amniotic fluid index above 25 cm. It is associated with fetal anomalies, maternal diabetes and multiple pregnancy.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (10, $x$Marked oligohydramnios detected in the second trimester is most classically associated with which fetal anomaly?$x$, $x$["Anencephaly","Bilateral renal agenesis","Duodenal atresia","Oesophageal atresia"]$x$, 1, $x$Fetal urine is the main source of liquor in the second half of pregnancy, so bilateral renal agenesis, or Potter syndrome, causes severe oligohydramnios. Anencephaly and the atresias are instead linked with polyhydramnios.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (11, $x$In which type of breech presentation are the hips flexed and both knees extended, making it the commonest variety?$x$, $x$["Frank breech","Complete breech","Footling breech","Knee presentation"]$x$, 0, $x$In frank or extended breech the thighs are flexed on the abdomen while the legs are extended over the trunk, with the buttocks presenting. It is the commonest breech type, seen especially in primigravidae with good uterine tone.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (12, $x$The type of episiotomy most widely practised in India, chosen because it is less likely to extend into the anal sphincter, is the$x$, $x$["Lateral episiotomy","Mediolateral episiotomy","J-shaped episiotomy","Median or midline episiotomy"]$x$, 1, $x$The mediolateral incision is directed away from the anus, reducing the risk of third and fourth degree extension into the sphincter and rectum. The median type heals better but carries a higher risk of anal extension.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (13, $x$Ventouse or vacuum extraction is generally avoided in a fetus of less than 34 weeks gestation mainly because of the risk of$x$, $x$["Erb's palsy","Subgaleal or intracranial haemorrhage","Facial nerve palsy","Fractured clavicle"]$x$, 1, $x$The preterm skull is soft and its vessels are fragile, so vacuum application increases the risk of subgaleal and intraventricular haemorrhage. For this reason forceps or caesarean section are preferred in very preterm deliveries.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (14, $x$The oral levonorgestrel emergency contraceptive pill is most effective when taken within how long after unprotected intercourse?$x$, $x$["Within 7 days","Within 2 weeks","Within 72 hours","Within 10 days"]$x$, 2, $x$Levonorgestrel emergency contraception should be taken as early as possible and within 72 hours of unprotected sex, with efficacy declining as time passes. It works mainly by inhibiting or delaying ovulation, not by disrupting an established pregnancy.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (15, $x$Menopause is confirmed clinically only after menstruation has ceased continuously for at least$x$, $x$["6 months","12 months","3 months","24 months"]$x$, 1, $x$Menopause is defined retrospectively as amenorrhoea for 12 consecutive months in the absence of any other cause. The average age of natural menopause in India is around 45 to 50 years, somewhat earlier than in Western populations.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (16, $x$On a standard growth chart, the single most useful indicator of an emerging nutritional problem in a child is$x$, $x$["The heights of the parents","The child's recorded length at birth","The direction and trend of the weight-for-age curve over time","A single weight reading below the 50th percentile"]$x$, 2, $x$Serial plotting matters far more than any single reading; a weight curve that flattens or falls, crossing percentile lines downward, signals growth faltering. One point below the median may be perfectly normal for that individual child.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (17, $x$The mature pincer grasp, using the tip of the thumb and index finger to pick up a small object, is normally acquired by about$x$, $x$["4 months","6 months","9 to 10 months","15 months"]$x$, 2, $x$The neat pincer grasp develops around 9 to 10 months, following the immature palmar grasp at about 6 months and raking at 7 to 8 months. Its appearance reflects normal fine-motor and neurological maturation.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (18, $x$Which of the following is a true contraindication to administering a live vaccine such as BCG or oral polio?$x$, $x$["Mild fever with cough and cold","Breastfeeding","Malnutrition","Severe immunodeficiency, such as symptomatic HIV or AIDS"]$x$, 3, $x$Live vaccines are contraindicated in severe immunodeficiency because the attenuated organism may itself cause disease. Minor illness, malnutrition and breastfeeding are not contraindications and represent common missed-opportunity myths.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (19, $x$Under IMNCI, a child with diarrhoea who is restless or irritable, has sunken eyes, drinks eagerly, and whose skin pinch goes back slowly is classified as having$x$, $x$["Severe dehydration","Persistent diarrhoea","Some dehydration","No dehydration"]$x$, 2, $x$The combination of restlessness, sunken eyes, eager drinking and a slow skin pinch indicates some dehydration, managed with ORS under Treatment Plan B. Severe dehydration instead shows lethargy, inability to drink and a very slowly returning skin pinch.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (20, $x$In the IMNCI classification of a child aged 2 months to 5 years with cough, the presence of lower chest wall indrawing indicates$x$, $x$["Bronchial asthma","Severe pneumonia or very severe disease requiring referral","No pneumonia, cough or cold","Pneumonia to be treated at home"]$x$, 1, $x$Lower chest wall indrawing is a danger sign that classifies the illness as severe pneumonia, requiring a first dose of antibiotic and urgent referral. This is more serious than the classification based on raised respiratory rate alone.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (21, $x$Which intestinal helminth is the most important parasitic cause of iron-deficiency anaemia in children through chronic intestinal blood loss?$x$, $x$["Enterobius vermicularis or pinworm","Hookworm, Ancylostoma or Necator","Taenia saginata","Ascaris lumbricoides"]$x$, 1, $x$Hookworms attach to the intestinal mucosa and suck blood, producing chronic occult blood loss and iron-deficiency anaemia. Pinworm mainly causes perianal itching and Ascaris may cause obstruction, but neither typically causes significant anaemia.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (22, $x$In the inpatient management of a child with severe acute malnutrition, the most immediately life-threatening complications to prevent during the stabilisation phase are$x$, $x$["Constipation","Excess protein intake","Slow weight gain","Hypoglycaemia and hypothermia"]$x$, 3, $x$During stabilisation, hypoglycaemia, hypothermia and dehydration are the main killers, so frequent F-75 feeds and warmth are essential. High-calorie catch-up feeding is deliberately delayed to avoid precipitating refeeding syndrome and cardiac failure.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (23, $x$A newborn with a cleft lip and palate mainly has difficulty with feeding because of$x$, $x$["Lack of hunger","Complete oesophageal obstruction","Absence of the swallowing reflex","Inability to generate adequate suction"]$x$, 3, $x$The oro-nasal communication prevents an effective seal and negative pressure, so the baby cannot suck efficiently and may regurgitate through the nose or aspirate. Special cleft feeders, spoon or paladai feeding and an upright position help until surgical repair.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (24, $x$Down syndrome, the commonest chromosomal cause of intellectual disability, results from$x$, $x$["Monosomy X","Trisomy 21","Trisomy 13","Trisomy 18"]$x$, 1, $x$Down syndrome is caused by an extra chromosome 21, or trisomy 21, most often from meiotic non-disjunction and commoner with advanced maternal age. Typical features include hypotonia, a flat facial profile, upslanting palpebral fissures and a single palmar crease.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (25, $x$Peri-conceptional supplementation of which vitamin markedly reduces the risk of neural tube defects such as spina bifida?$x$, $x$["Vitamin A","Vitamin B12","Vitamin K","Folic acid"]$x$, 3, $x$Adequate folic acid before conception and in early pregnancy prevents failure of neural tube closure, lowering the risk of spina bifida and anencephaly. A daily dose of about 400 micrograms is advised, with higher doses for high-risk women.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (26, $x$Regarding a simple febrile convulsion, which statement is correct?$x$, $x$["It usually lasts more than 30 minutes","It commonly leaves permanent neurological damage","It typically occurs in infants under 3 months of age","It occurs between 6 months and 5 years and is generally benign"]$x$, 3, $x$Simple febrile convulsions occur between 6 months and 5 years, are brief at under 15 minutes, generalised, and do not recur within 24 hours. They carry an excellent prognosis with no lasting brain damage, and management centres on controlling fever and parental reassurance.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (27, $x$In a child who has swallowed a corrosive substance such as an acid or alkali, the first-aid measure that is contraindicated is$x$, $x$["Inducing vomiting","Removing any contaminated clothing","Taking the child urgently to hospital","Keeping the child calm"]$x$, 0, $x$Inducing vomiting after corrosive ingestion is dangerous because it re-exposes the oesophagus to the caustic agent and risks aspiration and perforation. The child should be kept calm and taken urgently to hospital with the container or label for identification.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$)
) as v(pos, question, options, ci, exp, topic, diff);

commit;

-- Expect: 178 rows inserted across 6 batches.
-- Check with:  select topic, difficulty, count(*) from questions group by 1,2 order by 1,2;
