-- ═══════════════════════════════════════════════════════
-- Question bank import
-- Run in: Supabase → SQL Editor → New query → Run
--
-- Wrapped in a transaction: if any row fails, nothing is
-- inserted and the bank is left exactly as it was.
-- Running it twice inserts the questions twice, so run once.
-- ═══════════════════════════════════════════════════════

begin;

-- 11-community-epi-system.txt — 25 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 11 — Community Health: epidemiology, biostatistics, health system$x$, $x$Community Health Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The proportion of new cases of a disease occurring in a defined population over a specified period is the$x$, $x$["Case fatality rate","Prevalence rate","Attack rate","Incidence rate"]$x$, 3, $x$Incidence counts new cases arising over a period and measures the risk of developing the disease. Prevalence counts all existing cases at a point in time and reflects both incidence and duration.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (1, $x$Point prevalence is best defined as the number of$x$, $x$["Deaths among diagnosed cases","Existing cases at a given point in time, per population at that point","New cases occurring during a period","Cases exposed to a specific source"]$x$, 1, $x$Point prevalence is all current cases, old and new, divided by the population at that moment. It rises when incidence increases or when cases live longer, and falls with cure or death.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (2, $x$In an outbreak investigation, the attack rate is calculated as the number of$x$, $x$["New cases per 1000 mid-year population per year","Exposed persons divided by cases","Cases divided by the total population at risk, over the outbreak period","Deaths divided by cases"]$x$, 2, $x$The attack rate is a form of incidence used in a defined epidemic over a limited time, expressed as cases per persons exposed, usually as a percentage. Comparing attack rates across exposures points to the likely source.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (3, $x$The type of epidemiological study that begins with the outcome and looks backward for exposure is a$x$, $x$["Randomised controlled trial","Cohort study","Cross-sectional study","Case-control study"]$x$, 3, $x$A case-control study compares people with the disease to those without, looking back at past exposures, and yields an odds ratio. It is efficient for rare diseases and for those with a long latent period.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (4, $x$A cohort study measures association using the$x$, $x$["Relative risk","Correlation coefficient","Odds ratio","Prevalence ratio"]$x$, 0, $x$A cohort follows exposed and unexposed groups forward to see who develops disease, giving incidence in each and therefore relative risk. Case-control studies, which cannot measure incidence directly, use the odds ratio instead.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (5, $x$The gold standard study design for evaluating a new treatment is the$x$, $x$["Case report","Randomised controlled trial","Ecological study","Case series"]$x$, 1, $x$Random allocation balances known and unknown confounders between groups, so differences in outcome can be attributed to the intervention. Blinding and allocation concealment further protect against bias.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (6, $x$The positive predictive value of a screening test is the probability that a person with a positive result$x$, $x$["Will be missed by the test","Truly has the disease","Truly does not have the disease","Was correctly exposed"]$x$, 1, $x$Positive predictive value depends on the test's sensitivity and specificity and, crucially, on the prevalence of the disease. In a low-prevalence population even a good test throws up many false positives, lowering the predictive value.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (7, $x$A screening test that gives the same result on repeated testing is said to be$x$, $x$["Valid","Sensitive","Specific","Reliable"]$x$, 3, $x$Reliability is consistency on repetition, whereas validity is the ability to measure the truth. A test can be highly reliable yet consistently wrong, so both properties are assessed separately.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (8, $x$Lead time bias in screening refers to$x$, $x$["Over-diagnosis of harmless disease","Detecting disease earlier without changing the actual outcome, so survival only appears longer","Errors in recording the time of death","Selecting healthier volunteers for screening"]$x$, 1, $x$Screening advances the moment of diagnosis, so survival measured from diagnosis looks longer even if death occurs at the same time. Sound evaluation of a screening programme therefore uses mortality, not survival time.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (9, $x$The standardised death rate is used to$x$, $x$["Count only deaths in hospital","Compare mortality between populations with different age structures","Measure infant deaths alone","Record cause-specific mortality only"]$x$, 1, $x$Crude death rates cannot be compared fairly when populations differ in age, since age strongly affects death. Standardisation applies each population's rates to a common reference age structure, removing that distortion.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (10, $x$The under-five mortality rate is expressed per$x$, $x$["1000 mid-year population","1000 children under five","100000 live births","1000 live births"]$x$, 3, $x$The under-five mortality rate is deaths before the fifth birthday per 1000 live births, a key indicator of child health and of the effectiveness of maternal and child services. It is distinct from the child death rate, which uses the population aged 1 to 4.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (11, $x$The neonatal period covers the first$x$, $x$["42 days of life","7 days of life","24 hours of life","28 days of life"]$x$, 3, $x$The neonatal period is the first 28 days, subdivided into early neonatal, the first 7 days, and late neonatal. Most neonatal deaths occur in the first week, which is why early care matters so much.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (12, $x$The general fertility rate uses as its denominator the number of$x$, $x$["Total population","Women in the reproductive age group, usually 15 to 49 years","Live births","Married women only"]$x$, 1, $x$Unlike the crude birth rate, which uses the whole population, the general fertility rate restricts the denominator to women aged 15 to 49, giving a more refined measure of fertility.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (13, $x$A total fertility rate of about 2.1 in a population is significant because it represents$x$, $x$["The replacement level of fertility","Rapid population growth","A declining and ageing population immediately","Zero births"]$x$, 0, $x$A total fertility rate near 2.1 children per woman just replaces the parents while allowing for childhood mortality, so the population eventually stabilises. India reached around this level nationally, though it varies by state.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (14, $x$The dependency ratio compares the population aged under 15 and over 65 to those$x$, $x$["Living in urban areas","Who are employed only","Who are literate","In the working ages, roughly 15 to 64"]$x$, 3, $x$The dependency ratio expresses the non-working young and old against the economically productive ages, indicating the burden of support. A youthful population and an ageing one both raise it, for different reasons.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (15, $x$In the demographic cycle, the stage marked by a falling death rate while the birth rate stays high, producing rapid growth, is$x$, $x$["Early expanding","Low stationary","High stationary","Late expanding"]$x$, 0, $x$In the early expanding stage improved sanitation, nutrition and medicine cut deaths while births remain high, so the population grows fastest. In the late expanding stage the birth rate too begins to fall.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (16, $x$A community health centre in India is designed to serve a population of approximately$x$, $x$["5000","30000","120000","500000"]$x$, 2, $x$A community health centre covers about 120,000 people in the plains and 80,000 in hilly or tribal areas, acting as a first referral unit with specialists and beds. Below it sit the primary health centre and the sub-centre.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (17, $x$The first referral unit providing specialist care such as caesarean section and blood transfusion in rural India is the$x$, $x$["Primary health centre","Sub-centre","Community health centre","Anganwadi"]$x$, 2, $x$The community health centre is designated as the first referral unit, staffed with specialists in surgery, medicine, obstetrics and paediatrics, with an operation theatre, laboratory and blood storage. The primary health centre refers upward to it.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (18, $x$The most peripheral institution and the first point of contact between the primary health care system and the community is the$x$, $x$["Sub-centre","District hospital","Community health centre","Primary health centre"]$x$, 0, $x$The sub-centre, staffed by an auxiliary nurse midwife and a male health worker, is the most peripheral contact point, focused on maternal and child health, family welfare, immunisation and control of communicable disease.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (19, $x$The auxiliary nurse midwife at a sub-centre is primarily responsible for$x$, $x$["Maternal and child health, immunisation and family welfare services","Laboratory diagnosis of malaria only","District-level administration","Performing major surgery"]$x$, 0, $x$The ANM delivers antenatal and postnatal care, conducts and refers deliveries, gives immunisations, promotes family planning and treats minor ailments. She is the backbone of maternal and child health at the periphery.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (20, $x$In India, the multipurpose health worker scheme integrates the functions of$x$, $x$["Doctors and specialists","Hospital administrators","Previously separate unipurpose workers such as malaria, family planning and smallpox staff","Private practitioners"]$x$, 2, $x$The multipurpose worker scheme, following the Kartar Singh committee, merged the many single-purpose field workers into male and female multipurpose workers, so one worker delivers a range of services to each family rather than several visiting separately.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (21, $x$Primary health care was declared as the key to attaining Health for All at the international conference held at$x$, $x$["Geneva","Bangkok","Alma-Ata","Ottawa"]$x$, 2, $x$The 1978 Alma-Ata declaration proclaimed primary health care as the route to Health for All. The later Ottawa Charter of 1986 developed the framework for health promotion.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (22, $x$Health promotion, as described in the Ottawa Charter, is best understood as$x$, $x$["Building more hospitals","Providing free medicines","Treating disease early","The process of enabling people to increase control over and improve their health"]$x$, 3, $x$The Ottawa Charter defines health promotion as enabling people to gain control over the determinants of health, through healthy public policy, supportive environments, community action, personal skills and reoriented services.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (23, $x$The measure of the average number of years a person is expected to live, widely used to summarise a population's health, is$x$, $x$["Total fertility rate","Crude death rate","Infant mortality rate","Life expectancy at birth"]$x$, 3, $x$Life expectancy at birth is the average number of years a newborn would live under current mortality conditions, a summary indicator sensitive to deaths at all ages, especially in infancy.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (24, $x$The disability-adjusted life year, or DALY, combines$x$, $x$["The number of hospital beds and doctors","Years of life lost to premature death and years lived with disability","Only years of life lost to death","Income and literacy"]$x$, 1, $x$One DALY is one lost year of healthy life, summing years lost to premature mortality and years lived with disability weighted for severity. It allows the total burden of a disease, fatal and non-fatal, to be compared.$x$, $x$Community Health Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 12-community-programmes.txt — 25 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 12 — Community Health: national programmes, MCH, environment, nutrition$x$, $x$Community Health Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The national tuberculosis programme in India now aims to end TB by$x$, $x$["2025","2030","2040","2050"]$x$, 0, $x$The National TB Elimination Programme targets ending TB in India by 2025, five years ahead of the global Sustainable Development Goal of 2030. It relies on early diagnosis, assured treatment, patient support and active case finding.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (1, $x$The first-line treatment for a new case of pulmonary tuberculosis uses$x$, $x$["Antibiotics for one week","A combination of at least four drugs in the intensive phase","A single drug for six months","Surgery"]$x$, 1, $x$Standard treatment begins with isoniazid, rifampicin, pyrazinamide and ethambutol in the intensive phase, then continues with fewer drugs. Multiple drugs prevent the selection of resistant organisms, and the full course must be completed.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (2, $x$Under the national programme, leprosy is confirmed as multibacillary when there are$x$, $x$["A single skin lesion","Only nerve thickening","No skin lesions","More than five skin lesions"]$x$, 3, $x$Leprosy is classified for treatment by lesion count: up to five lesions is paucibacillary and more than five is multibacillary, which needs longer multidrug therapy. The classification guides the duration of treatment.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (3, $x$The vector of dengue, which breeds in clean stored water, is$x$, $x$["Culex mosquito","Anopheles mosquito","Housefly","Aedes aegypti"]$x$, 3, $x$Aedes aegypti, a day-biting mosquito that breeds in clean water in containers, coolers and discarded tyres, transmits dengue, chikungunya, Zika and yellow fever. Source reduction by removing breeding sites is the mainstay of control.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (4, $x$The warning signs of dengue that indicate progression to severe disease include$x$, $x$["Mild fever only","A single episode of headache","Severe abdominal pain, persistent vomiting and bleeding","Improved appetite"]$x$, 2, $x$Warning signs such as severe abdominal pain, persistent vomiting, mucosal bleeding, lethargy and a rapidly falling platelet count herald plasma leakage and shock. Recognising them prompts urgent hospital care and fluid management.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (5, $x$In the national immunisation schedule, the pentavalent vaccine protects against diphtheria, pertussis, tetanus, hepatitis B and$x$, $x$["Polio","Tuberculosis","Haemophilus influenzae type b","Measles"]$x$, 2, $x$The pentavalent vaccine combines DPT with hepatitis B and Haemophilus influenzae type b, given at 6, 10 and 14 weeks. Combining antigens reduces the number of injections and improves coverage.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (6, $x$A fully immunised child under the national schedule has received all due vaccines by the age of$x$, $x$["1 year","6 weeks","5 years","6 months"]$x$, 0, $x$A child is counted as fully immunised when BCG, three doses of pentavalent and OPV, and the first measles-rubella dose have been received by one year of age. Coverage by one year is a standard programme indicator.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (7, $x$Pulse polio immunisation is based on the strategy of$x$, $x$["Giving oral polio vaccine to all children under five on fixed national immunisation days","Treating cases after paralysis","Injecting vaccine once in a lifetime","Vaccinating only sick children"]$x$, 0, $x$Pulse polio delivers oral polio vaccine to every child under five on national immunisation days regardless of prior doses, interrupting transmission by rapidly raising community immunity. It underpinned India's polio-free certification in 2014.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (8, $x$Iron and folic acid supplementation in pregnancy is given primarily to prevent$x$, $x$["Hypertension","Urinary infection","Gestational diabetes","Nutritional anaemia"]$x$, 3, $x$Anaemia is very common in pregnancy and raises the risk of preterm birth, low birth weight and maternal death. Routine iron and folic acid, with deworming, is a core antenatal intervention, and folic acid also prevents neural tube defects.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (9, $x$The most sensitive indicator of the overall health status of a community is generally taken to be the$x$, $x$["Infant mortality rate","Sex ratio","Literacy rate","Crude birth rate"]$x$, 0, $x$The infant mortality rate responds to nutrition, maternal health, sanitation, immunisation and access to care, so it captures the overall conditions of a society and is widely used as a summary health indicator.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (10, $x$The permissible upper limit of fluoride in drinking water, above which dental and skeletal fluorosis occur, is about$x$, $x$["0.5 mg per litre","1.0 to 1.5 mg per litre","5 mg per litre","10 mg per litre"]$x$, 1, $x$Fluoride around 1 mg per litre protects against dental caries, but above roughly 1.5 mg per litre it mottles the teeth and, at higher and prolonged levels, damages bone. Both too little and too much are undesirable.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (11, $x$The most important indicator of recent faecal contamination of water is the presence of$x$, $x$["Fluoride","Chlorine","Total dissolved solids","Escherichia coli"]$x$, 3, $x$Escherichia coli is a normal gut organism, so its presence in water signals recent faecal contamination and the possible presence of pathogens. It is the standard bacteriological indicator of drinking water safety.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (12, $x$In biomedical waste segregation, human anatomical waste and soiled waste requiring incineration are placed in the$x$, $x$["White puncture-proof container","Blue container","Yellow container","Red container"]$x$, 2, $x$Under the biomedical waste rules, yellow is for anatomical and infectious soiled waste destined for incineration, red for contaminated recyclable plastics, white for sharps and blue for glassware and metallic implants.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (13, $x$The recommended method for final disposal of the placenta and other anatomical hospital waste is$x$, $x$["Flushing down the drain","Open dumping","Discarding with general refuse","Deep burial or incineration as infectious waste"]$x$, 3, $x$Anatomical waste is infectious and is treated as yellow-category biomedical waste, disposed of by incineration or, where that is unavailable, by deep burial in a secure pit. It must never enter the general waste stream.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (14, $x$Grade I protein energy malnutrition by the Indian Academy of Pediatrics classification corresponds to a weight for age of$x$, $x$["70 to 80 per cent of expected","50 to 60 per cent of expected","90 to 100 per cent of expected","Below 50 per cent of expected"]$x$, 0, $x$The IAP classification grades malnutrition by weight for age: 70 to 80 per cent is grade I, 60 to 70 grade II, 50 to 60 grade III and below 50 per cent grade IV. It is a simple field tool for identifying and grading undernutrition.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (15, $x$Mid-upper arm circumference is used in the community to screen for acute malnutrition in children aged$x$, $x$["6 months to 5 years","Under 6 months","5 to 10 years","Over 10 years"]$x$, 0, $x$In children aged 6 to 59 months the mid-upper arm circumference changes little with age, so a fixed cut-off works: below 11.5 cm indicates severe acute malnutrition. It is quick, needs no scales and is ideal for field screening.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (16, $x$Vitamin A deficiency is a leading preventable cause of$x$, $x$["Goitre","Deafness","Rickets","Childhood blindness"]$x$, 3, $x$Vitamin A deficiency causes night blindness progressing to xerophthalmia and irreversible corneal damage, and it also worsens infection. Prophylactic vitamin A given six-monthly to young children prevents it.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (17, $x$The addition of iodine to salt is the national strategy to prevent$x$, $x$["Fluorosis","Vitamin A deficiency","Iodine deficiency disorders such as goitre and cretinism","Anaemia"]$x$, 2, $x$Universal salt iodisation is the cornerstone of preventing iodine deficiency disorders, which range from goitre to the severe and irreversible mental and physical impairment of cretinism when deficiency occurs in pregnancy.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (18, $x$The incubation period of measles, from exposure to the appearance of rash, is approximately$x$, $x$["30 days","1 to 2 days","10 to 14 days","3 months"]$x$, 2, $x$Measles has an incubation period of about 10 to 14 days. The patient is infectious from a few days before the rash until about four days after it appears, which is why isolation and prompt vaccination of contacts matter.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (19, $x$Chickenpox is caused by the$x$, $x$["Rubella virus","Varicella zoster virus","Measles virus","Mumps virus"]$x$, 1, $x$The varicella zoster virus causes chickenpox on first infection and, on reactivation years later, herpes zoster or shingles. Its lesions appear in successive crops, giving the characteristic mix of papules, vesicles and crusts.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (20, $x$The most effective single strategy to interrupt the faeco-oral transmission of diseases such as cholera and typhoid is$x$, $x$["Bed nets","Mass antibiotic use","Vaccination alone","Improved sanitation and safe water supply"]$x$, 3, $x$Faeco-oral diseases spread through contaminated water and food, so safe water, sanitary excreta disposal, hand hygiene and food safety break the chain most effectively. Vaccines and treatment supplement, but do not replace, these environmental measures.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (21, $x$A sudden increase in cases of a disease clearly in excess of what is normally expected in a community is a/an$x$, $x$["Epidemic","Sporadic occurrence","Endemic","Pandemic across continents"]$x$, 0, $x$An epidemic is the occurrence of cases clearly above the expected number for that place and time. When such an epidemic spreads across several countries and continents it is called a pandemic.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (22, $x$Convalescent carriers are individuals who$x$, $x$["Have never had the disease but harbour the organism","Are immune and non-infectious","Continue to shed the organism during recovery after clinical illness","Show symptoms permanently"]$x$, 2, $x$A convalescent carrier keeps excreting the organism during recovery, as in typhoid. Carriers may also be incubatory, shedding before symptoms, or healthy, never developing illness, and all can maintain transmission unnoticed.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (23, $x$Passive immunity is conferred by$x$, $x$["Administering preformed antibodies such as immunoglobulin or antiserum","Giving a vaccine","A course of antibiotics","Natural infection"]$x$, 0, $x$Passive immunity supplies ready-made antibodies, as in anti-tetanus or anti-rabies immunoglobulin and in the transfer of maternal antibody to the fetus. It acts at once but is short-lived, unlike the durable protection of active immunisation.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (24, $x$The observation period for a person exposed to a suspected case, kept under surveillance for the maximum incubation period, is called$x$, $x$["Disinfection","Isolation","Quarantine","Notification"]$x$, 2, $x$Quarantine restricts the movement of apparently well people who have been exposed, for the longest usual incubation period, to watch for illness. Isolation, by contrast, separates those who are already sick to prevent spread.$x$, $x$Community Health Nursing$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 13-gap-fillers.txt — 23 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 13 — filling thin filter cells: Mental Health (easy), and breadth across subjects$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$A state of calm alertness in which a person can attend, learn and solve problems best describes$x$, $x$["Panic","Depersonalisation","Mild anxiety","Severe anxiety"]$x$, 2, $x$Mild anxiety sharpens attention and can improve learning and performance. As anxiety rises to moderate, severe and panic levels, the field of perception narrows until the person can no longer function.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (1, $x$Empathy in the nurse-patient relationship means$x$, $x$["Feeling sorry for the patient","Agreeing with everything the patient says","Ignoring the patient's emotions","Understanding and sharing the patient's feelings while staying objective"]$x$, 3, $x$Empathy is entering into and understanding another's feelings while keeping enough objectivity to help. It differs from sympathy, which is feeling sorry for someone and can cloud professional judgement.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (2, $x$The best therapeutic response when a patient is silent during an interview is to$x$, $x$["Fill every pause with questions","End the session immediately","Change the subject at once","Allow the silence, showing attentive presence"]$x$, 3, $x$Silence is a valuable therapeutic technique that gives the patient time to think and to gather difficult feelings. Rushing to fill it can cut off important disclosures, whereas attentive presence conveys acceptance.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (3, $x$Good mental health is best described as$x$, $x$["A state of well-being in which a person copes with normal stresses, works productively and contributes to the community","Complete independence from others","The mere absence of mental illness","Never feeling sad or anxious"]$x$, 0, $x$WHO defines mental health as a state of well-being in which the individual realises their abilities, copes with normal stresses, works productively and contributes to their community. It is more than simply the absence of disorder.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (4, $x$A recurrent, unwanted thought that intrudes despite the person's efforts to resist it is a/an$x$, $x$["Delusion","Illusion","Obsession","Hallucination"]$x$, 2, $x$An obsession is an intrusive, repetitive thought the person recognises as their own and tries to resist, unlike a delusion, which is a fixed false belief held with conviction and without insight.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (5, $x$Rapport in a therapeutic relationship refers to$x$, $x$["A relationship of trust and mutual understanding","A prescription of medication","A physical examination","A legal contract"]$x$, 0, $x$Rapport is the sense of trust, harmony and understanding between nurse and patient. Establishing it early, through warmth, respect and genuineness, is the foundation on which all later therapeutic work rests.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (6, $x$The defence mechanism of denial involves$x$, $x$["Channelling urges into acceptable activity","Returning to childlike behaviour","Blaming others for one's own faults","Refusing to accept a painful reality"]$x$, 3, $x$Denial protects the person by refusing to acknowledge a distressing fact, as when a newly diagnosed patient insists the results must be wrong. It is common early in grief and usually gives way as the person adjusts.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (7, $x$A person's awareness of time, place and person is assessed as$x$, $x$["Memory","Insight","Judgement","Orientation"]$x$, 3, $x$Orientation to time, place and person is a basic part of the mental state examination and of consciousness. Disorientation, especially to time first, is an early sign of an acute confusional state.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (8, $x$The normal respiratory rate in a resting adult is$x$, $x$["6 to 10 breaths per minute","12 to 20 breaths per minute","25 to 30 breaths per minute","30 to 40 breaths per minute"]$x$, 1, $x$A healthy adult breathes 12 to 20 times per minute at rest. Below 12 is bradypnoea and above 20 is tachypnoea, both of which warrant assessment for an underlying cause.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (9, $x$The largest organ of the human body is the$x$, $x$["Skin","Lung","Liver","Brain"]$x$, 0, $x$The skin is the largest organ, forming a protective barrier and playing roles in temperature regulation, sensation, immunity and vitamin D synthesis. The liver is the largest internal solid organ.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (10, $x$The master gland of the endocrine system, which controls several other glands, is the$x$, $x$["Pancreas","Thyroid","Adrenal","Pituitary"]$x$, 3, $x$The pituitary is called the master gland because its hormones regulate the thyroid, adrenal cortex, gonads and more. It is itself directed by the hypothalamus, to which it is closely connected.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (11, $x$The universal recipient blood group, able to receive red cells from any ABO group, is$x$, $x$["AB positive","B positive","O positive","A positive"]$x$, 0, $x$Group AB has no anti-A or anti-B antibodies in the plasma, so it can receive red cells of any ABO group, making AB the universal recipient. Group O negative, lacking A, B and RhD antigens, is the universal red cell donor.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (12, $x$The vitamin synthesised by bacteria in the large intestine and needed for blood clotting is$x$, $x$["Vitamin B12","Vitamin A","Vitamin K","Vitamin C"]$x$, 2, $x$Gut bacteria produce vitamin K, which the liver needs to make clotting factors II, VII, IX and X. Newborns, whose gut is not yet colonised, are given vitamin K at birth to prevent haemorrhagic disease.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (13, $x$The first sign a nurse should act on when a patient's oxygen saturation is falling is$x$, $x$["To document it at the end of the shift","To remove the pulse oximeter","To assess the patient, check the airway and breathing, and give oxygen as needed","To wait for the next scheduled observation"]$x$, 2, $x$A falling saturation calls for immediate bedside assessment of airway, breathing and circulation and appropriate oxygen, not delay. Confirming the reading and looking at the whole patient comes before charting.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (14, $x$The correct sequence for putting on personal protective equipment is$x$, $x$["Goggles, gloves, gown, mask","Mask, gloves, gown, goggles","Gown, mask, goggles, gloves","Gloves, gown, mask, goggles"]$x$, 2, $x$Protective equipment is donned gown first, then mask or respirator, then eye protection, and gloves last so they cover the gown cuffs. Removal reverses the principle, taking off the most contaminated items first while avoiding self-contamination.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (15, $x$When a medication error reaches a patient, the nurse's first responsibility is to$x$, $x$["Assess the patient, ensure safety, report the error and document it honestly","Wait to see if any harm develops","Blame the pharmacy","Hide the error to avoid blame"]$x$, 0, $x$Patient safety comes first, so the nurse assesses and monitors the patient, informs the prescriber, and reports the incident truthfully. Open reporting supports learning and system improvement rather than concealment.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (16, $x$A wound healing by primary intention is one that$x$, $x$["Is heavily infected","Heals only with a skin graft","Is left open to granulate from the base","Has clean, approximated edges, such as a sutured surgical incision"]$x$, 3, $x$Primary intention healing occurs when clean wound edges are brought together, as with sutures, giving quick healing and minimal scarring. Wounds left open to fill with granulation tissue heal by secondary intention.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (17, $x$The earliest local sign of acute inflammation includes$x$, $x$["Dryness and scaling","Pallor and coldness","Numbness","Redness, heat, swelling and pain"]$x$, 3, $x$The classic signs of acute inflammation are redness, heat, swelling, pain and loss of function, caused by increased blood flow and vascular permeability. They reflect the body's protective response to injury or infection.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (18, $x$A diabetic patient should be taught to inspect which part of the body daily to prevent serious complications?$x$, $x$["The elbows","The back","The feet","The scalp"]$x$, 2, $x$Diabetic neuropathy and poor circulation make foot ulcers and infection common and easily missed, so daily inspection, good footwear and prompt care of any lesion are essential to prevent amputation.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (19, $x$The recommended position for a woman in the later stages of pregnancy to improve blood flow to the fetus is$x$, $x$["Standing","Prone","Left lateral","Supine, lying flat on the back"]$x$, 2, $x$Lying on the back late in pregnancy lets the heavy uterus compress the inferior vena cava, reducing venous return and fetal blood flow. The left lateral position relieves this pressure and improves circulation to the placenta.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (20, $x$The first breastfeed for a healthy newborn should ideally be initiated$x$, $x$["Within the first hour of birth","After the first bath","Only after the cord falls off","After 24 hours"]$x$, 0, $x$Early initiation of breastfeeding within the first hour gives the baby protective colostrum, promotes bonding, stimulates milk production and helps the uterus contract. It is a key element of newborn care.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (21, $x$The most common cause of neonatal death in India, alongside infection and birth asphyxia, is$x$, $x$["Prematurity and low birth weight","Injury","Congenital heart disease","Poisoning"]$x$, 0, $x$Prematurity and low birth weight, together with infections such as sepsis and pneumonia and with birth asphyxia, account for most neonatal deaths. Warmth, early feeding, hygiene and prompt treatment of infection address them.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (22, $x$The screening test routinely offered to all newborns to detect congenital hypothyroidism relies on measuring$x$, $x$["Bilirubin","Thyroid stimulating hormone","Haemoglobin","Blood glucose"]$x$, 1, $x$Congenital hypothyroidism causes irreversible intellectual disability if untreated, but is easily corrected with thyroxine if caught early. Newborn screening measures thyroid stimulating hormone, which is raised in the condition.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

commit;

-- Expect: 73 rows inserted across 3 batches.
-- Check with:  select topic, difficulty, count(*) from questions group by 1,2 order by 1,2;
