-- ═══════════════════════════════════════════════════════
-- Question bank import
-- Run in: Supabase → SQL Editor → New query → Run
--
-- Wrapped in a transaction: if any row fails, nothing is
-- inserted and the bank is left exactly as it was.
-- Running it twice inserts the questions twice, so run once.
-- ═══════════════════════════════════════════════════════

begin;

-- 01-basic-sciences.txt — 25 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 1 — Anatomy, Physiology, Nutrition, Fundamentals$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The functional unit of the kidney is$x$, $x$["Hepatocyte","Neuron","Alveolus","Nephron"]$x$, 3, $x$Each kidney contains about one million nephrons, made up of a glomerulus and its tubule. The neuron is the functional unit of the nervous system, the alveolus of the lung, and the hepatocyte of the liver.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (1, $x$Which chamber of the heart pumps blood into the aorta?$x$, $x$["Left atrium","Right ventricle","Right atrium","Left ventricle"]$x$, 3, $x$The left ventricle ejects oxygenated blood into the aorta and has the thickest myocardium because it works against systemic pressure. The right ventricle pumps into the pulmonary artery at much lower pressure.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (2, $x$The normal pH range of arterial blood is$x$, $x$["7.05 to 7.15","7.25 to 7.35","7.35 to 7.45","7.45 to 7.55"]$x$, 2, $x$Arterial pH is tightly held between 7.35 and 7.45. Below 7.35 is acidaemia and above 7.45 is alkalaemia. This narrow range is defended by buffers, the lungs through carbon dioxide, and the kidneys through bicarbonate.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (3, $x$How many pairs of cranial nerves arise from the brain?$x$, $x$["10 pairs","12 pairs","24 pairs","31 pairs"]$x$, 1, $x$There are 12 pairs of cranial nerves. The 31 pairs refers to spinal nerves: 8 cervical, 12 thoracic, 5 lumbar, 5 sacral and 1 coccygeal.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (4, $x$Insulin is secreted by which cells of the pancreas?$x$, $x$["Delta cells of the islets of Langerhans","Acinar cells","Alpha cells of the islets of Langerhans","Beta cells of the islets of Langerhans"]$x$, 3, $x$Beta cells secrete insulin, alpha cells secrete glucagon and delta cells secrete somatostatin. The acinar cells produce digestive enzymes and belong to the exocrine pancreas.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (5, $x$Cardiac output is calculated as$x$, $x$["Stroke volume multiplied by blood pressure","Heart rate multiplied by stroke volume","Systolic pressure minus diastolic pressure","Heart rate divided by stroke volume"]$x$, 1, $x$Cardiac output equals heart rate times stroke volume, normally about 4 to 6 litres per minute in a resting adult. Systolic minus diastolic pressure gives the pulse pressure, not cardiac output.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (6, $x$The nerve supply to the diaphragm is the$x$, $x$["Phrenic nerve","Thoracodorsal nerve","Vagus nerve","Intercostal nerves"]$x$, 0, $x$The phrenic nerve arises from cervical roots C3, C4 and C5 and is the sole motor supply to the diaphragm. This is why a high cervical cord injury above C3 stops spontaneous breathing.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (7, $x$The normal glomerular filtration rate in a healthy adult is approximately$x$, $x$["25 mL/min","60 mL/min","125 mL/min","300 mL/min"]$x$, 2, $x$Normal GFR is about 125 mL/min, or roughly 180 litres filtered per day, of which more than 99 per cent is reabsorbed. A GFR below 60 mL/min sustained for three months defines chronic kidney disease.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (8, $x$Erythropoietin, the hormone that stimulates red cell production, is secreted mainly by the$x$, $x$["Liver","Spleen","Kidney","Red bone marrow"]$x$, 2, $x$Peritubular interstitial cells of the kidney release erythropoietin in response to hypoxia. This is why anaemia is such a common feature of chronic kidney disease.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (9, $x$The total volume of cerebrospinal fluid in an adult is about$x$, $x$["15 mL","50 mL","150 mL","500 mL"]$x$, 2, $x$About 150 mL of CSF circulates at any time, produced by the choroid plexus at roughly 500 mL per day, so the whole volume is replaced several times daily.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (10, $x$Antidiuretic hormone is released from the$x$, $x$["Adrenal cortex","Anterior pituitary","Posterior pituitary","Thyroid gland"]$x$, 2, $x$ADH and oxytocin are synthesised in the hypothalamus and stored and released from the posterior pituitary. The anterior pituitary releases growth hormone, TSH, ACTH, FSH, LH and prolactin.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (11, $x$Renin is secreted by which structure?$x$, $x$["Juxtaglomerular cells of the kidney","Zona glomerulosa of the adrenal cortex","Parafollicular cells of the thyroid","Chief cells of the stomach"]$x$, 0, $x$Juxtaglomerular cells release renin when renal perfusion falls, starting the renin-angiotensin-aldosterone cascade. The zona glomerulosa secretes aldosterone in response to that cascade, further down the chain.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (12, $x$Normal intracranial pressure in an adult is$x$, $x$["0 to 3 mmHg","5 to 15 mmHg","20 to 30 mmHg","40 to 50 mmHg"]$x$, 1, $x$Normal ICP is 5 to 15 mmHg. Sustained pressure above 20 mmHg is treated as intracranial hypertension and threatens cerebral perfusion, which equals mean arterial pressure minus ICP.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (13, $x$A shift of the oxygen-haemoglobin dissociation curve to the right is caused by$x$, $x$["Acidosis, fever and increased 2,3-DPG","Alkalosis and hypothermia","Fetal haemoglobin","Decreased carbon dioxide and decreased 2,3-DPG"]$x$, 0, $x$A right shift means haemoglobin releases oxygen more readily to the tissues, and is produced by acidosis, raised carbon dioxide, fever and increased 2,3-DPG. Alkalosis, hypothermia and fetal haemoglobin shift the curve left, holding oxygen more tightly.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (14, $x$Which vitamin is required for the absorption of calcium from the intestine?$x$, $x$["Vitamin C","Vitamin A","Vitamin D","Vitamin K"]$x$, 2, $x$Vitamin D, in its active form calcitriol, increases intestinal absorption of calcium and phosphate. Its deficiency causes rickets in children and osteomalacia in adults.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (15, $x$The deficiency of which nutrient causes megaloblastic anaemia along with neurological signs?$x$, $x$["Iron","Vitamin K","Vitamin C","Vitamin B12"]$x$, 3, $x$Both folate and vitamin B12 deficiency produce a megaloblastic picture, but only B12 deficiency causes neurological damage such as subacute combined degeneration of the cord. Iron deficiency gives a microcytic hypochromic anaemia instead.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (16, $x$Kwashiorkor differs from marasmus chiefly by the presence of$x$, $x$["Normal serum albumin","Oedema with relatively preserved subcutaneous fat","Severe wasting with no oedema","Isolated vitamin A deficiency"]$x$, 1, $x$Kwashiorkor is protein deficiency with adequate calories, producing hypoalbuminaemia, oedema, a fatty liver and skin and hair changes. Marasmus is overall calorie deficiency producing gross wasting without oedema.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (17, $x$Which of these is the richest source of iron among the options?$x$, $x$["Cow's milk","Green leafy vegetables","Refined sugar","Polished rice"]$x$, 1, $x$Green leafy vegetables are a good plant source of iron, although the non-haem iron in them is less well absorbed than haem iron from animal foods. Milk is notably poor in iron, which is why prolonged exclusive milk feeding in toddlers causes anaemia.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (18, $x$The single most effective measure to prevent healthcare associated infection is$x$, $x$["Hand hygiene","Wearing gloves at all times","Routine prophylactic antibiotics","Daily mopping of floors with disinfectant"]$x$, 0, $x$Hand hygiene is the cheapest and most effective single intervention against healthcare associated infection. Gloves supplement it but do not replace it, and blanket antibiotic prophylaxis drives resistance.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (19, $x$The correct order of the nursing process is$x$, $x$["Planning, assessment, diagnosis, implementation, evaluation","Diagnosis, assessment, planning, evaluation, implementation","Assessment, planning, diagnosis, implementation, evaluation","Assessment, diagnosis, planning, implementation, evaluation"]$x$, 3, $x$The nursing process runs assessment, diagnosis, planning, implementation and evaluation, remembered as ADPIE. It is cyclical, so evaluation feeds back into reassessment.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (20, $x$Before administering digoxin, the nurse must specifically check the$x$, $x$["Apical pulse for one full minute","Temperature","Blood pressure","Respiratory rate"]$x$, 0, $x$Digoxin slows the heart, so the apical pulse is counted for a full minute and the dose withheld if it is below 60 beats per minute in an adult, with the doctor informed. Bradycardia may be the first sign of toxicity.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (21, $x$Which position is most appropriate for a patient in hypovolaemic shock?$x$, $x$["Prone position","High Fowler position","Supine with the legs elevated","Right lateral position"]$x$, 2, $x$Keeping the trunk flat and raising the legs improves venous return and perfusion of vital organs. Full head-down tilt is avoided because abdominal organs press on the diaphragm and impair ventilation.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (22, $x$The most reliable site for assessing pulse in an unresponsive adult during an emergency is the$x$, $x$["Carotid artery","Brachial artery","Dorsalis pedis artery","Radial artery"]$x$, 0, $x$The carotid is central and remains palpable when peripheral perfusion has failed, so it is the site used in adult basic life support. The brachial is the corresponding site in infants.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (23, $x$When applying a nasogastric tube, the correct method of confirming placement before feeding is$x$, $x$["Testing the pH of aspirate, with X-ray confirmation where required","Asking the patient to speak","Placing the tube end in water and watching for bubbles","Auscultating over the stomach while injecting air"]$x$, 0, $x$Testing gastric aspirate for an acidic pH, backed by radiography where doubt remains, is the accepted standard. The old "whoosh test" of auscultating injected air is unreliable and has been abandoned, because sound transmits even when the tube sits in the lung.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (24, $x$Sterilisation by autoclave is usually carried out at$x$, $x$["100 degrees Celsius for 5 minutes","60 degrees Celsius for 30 minutes","121 degrees Celsius at 15 psi for 15 to 20 minutes","180 degrees Celsius for 2 hours"]$x$, 2, $x$Moist heat under pressure at 121 degrees Celsius and 15 psi for 15 to 20 minutes kills spores as well as vegetative organisms. Dry heat at 160 to 180 degrees needs far longer, and boiling at 100 degrees does not reliably kill spores.$x$, $x$Nursing Foundations$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 02-medical-surgical.txt — 19 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 2 — Medical-Surgical Nursing$x$, $x$Medical-Surgical Nursing$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The classic triad of increased intracranial pressure is$x$, $x$["Hypotension, tachycardia and slow breathing","Hypoglycaemia, sweating and tremor","Hypertension, bradycardia and irregular respiration","Fever, tachycardia and hypotension"]$x$, 2, $x$This is Cushing's triad: rising systolic pressure with a widening pulse pressure, a slowing pulse and irregular respiration. It is a late and ominous sign of raised intracranial pressure and impending herniation.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (1, $x$The most common early sign of hypoxia is$x$, $x$["Clubbing","Bradycardia","Cyanosis","Restlessness"]$x$, 3, $x$Restlessness and altered behaviour appear early because the brain is exquisitely sensitive to falling oxygen. Cyanosis is a late sign, requiring about 5 g/dL of deoxygenated haemoglobin, and may never appear in an anaemic patient.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (2, $x$A patient with chronic obstructive pulmonary disease should receive oxygen$x$, $x$["Never, as it is contraindicated","At high flow, 10 to 12 litres per minute","Only during sleep","At controlled low flow, titrated to the target saturation"]$x$, 3, $x$In a patient who chronically retains carbon dioxide, uncontrolled high-flow oxygen can worsen hypercapnia, so oxygen is given in controlled low concentration and titrated to a target saturation, commonly 88 to 92 per cent. Oxygen is never withheld from a hypoxic patient.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (3, $x$The hallmark sign of left-sided heart failure is$x$, $x$["Pulmonary congestion with breathlessness","Ascites","Pedal oedema","Distended neck veins with hepatomegaly"]$x$, 0, $x$When the left ventricle fails, blood dams back into the lungs, causing dyspnoea, orthopnoea, paroxysmal nocturnal dyspnoea and crackles. Right-sided failure backs blood into the systemic veins, giving pedal oedema, raised jugular pressure, hepatomegaly and ascites.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (4, $x$The most specific cardiac biomarker for myocardial infarction is$x$, $x$["Lactate dehydrogenase","Creatine kinase MB","Serum troponin","Serum myoglobin"]$x$, 2, $x$Troponin I and T are the most specific and sensitive markers, rising within 3 to 6 hours and staying raised for up to two weeks. Myoglobin rises earliest but is entirely non-specific, and LDH is now obsolete for this purpose.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (5, $x$The priority nursing action for a patient with chest pain suggestive of myocardial infarction is$x$, $x$["Obtain a detailed dietary history","Give a full bed bath","Encourage ambulation to assess exercise tolerance","Position the patient upright, give oxygen if hypoxic and obtain an ECG"]$x$, 3, $x$The immediate priorities are to reduce cardiac workload and confirm the diagnosis quickly, so the patient is rested and positioned comfortably, oxygen given if saturations are low, an ECG taken within ten minutes and pain relieved. Exertion increases myocardial oxygen demand and is contraindicated.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (6, $x$Which finding in a patient on heparin therapy needs immediate attention?$x$, $x$["Haematuria with a falling platelet count","INR of 1.1","aPTT of 60 seconds","Mild bruising at the injection site"]$x$, 0, $x$Bleeding together with thrombocytopenia raises the possibility of heparin-induced thrombocytopenia, which paradoxically causes thrombosis and requires heparin to be stopped at once. An aPTT of 60 seconds is within the usual therapeutic range, and small injection-site bruises are expected.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (7, $x$The antidote for heparin overdose is$x$, $x$["Vitamin K","Naloxone","Protamine sulphate","Fresh frozen plasma alone"]$x$, 2, $x$Protamine sulphate binds and neutralises heparin. Vitamin K reverses warfarin, and naloxone reverses opioids. Knowing the drug-antidote pairs is a favourite examination point.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (8, $x$Which acid-base disturbance would you expect in a patient with prolonged vomiting?$x$, $x$["Respiratory acidosis","Respiratory alkalosis","Metabolic alkalosis","Metabolic acidosis"]$x$, 2, $x$Vomiting loses hydrogen and chloride ions from gastric juice, producing hypochloraemic metabolic alkalosis with hypokalaemia. Prolonged diarrhoea, by contrast, loses bicarbonate from below and causes metabolic acidosis.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (9, $x$The earliest sign of hypokalaemia on an ECG is$x$, $x$["Widened QRS complex","Tall peaked T waves","Shortened QT interval","Flattened T waves with a prominent U wave"]$x$, 3, $x$Low potassium flattens the T wave and brings out a U wave, and may cause ST depression and arrhythmias. Tall peaked T waves are the classic sign of the opposite problem, hyperkalaemia.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (10, $x$A patient with a chest drain in situ suddenly has the bottle knocked over and broken. The nurse should first$x$, $x$["Clamp the tube close to the chest wall and prepare a new drainage system","Reconnect the broken bottle","Remove the chest tube entirely","Run to call the doctor"]$x$, 0, $x$Brief clamping prevents air being drawn into the pleural space while a fresh sterile system is set up. Alternatively the tube end is submerged in sterile water. The drain is never removed by the nurse, and prolonged clamping risks a tension pneumothorax.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (11, $x$Dumping syndrome after gastric surgery is best managed by advising the patient to$x$, $x$["Sit upright and take a high carbohydrate diet","Fast for long periods between meals","Take large meals with plenty of fluid","Take small frequent dry meals, low in simple sugars, and lie down after eating"]$x$, 3, $x$Rapid emptying of hyperosmolar chyme into the jejunum pulls fluid into the gut. Small, dry, low-sugar, higher-protein meals with fluids taken between rather than with meals, followed by lying down, slow gastric emptying and reduce symptoms.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (12, $x$The most common cause of chronic kidney disease worldwide is$x$, $x$["Polycystic kidney disease","Urinary tract infection","Renal calculi","Diabetes mellitus"]$x$, 3, $x$Diabetic nephropathy is the leading cause, followed by hypertension. Together they account for the majority of patients reaching end-stage renal disease, which is why glycaemic and blood pressure control are central to prevention.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (13, $x$A patient on haemodialysis has an arteriovenous fistula in the left arm. The nurse should$x$, $x$["Apply a tight bandage over the fistula","Keep the arm strictly immobilised","Avoid venepuncture, blood pressure and intravenous lines in that arm, and check the thrill","Record blood pressure from the left arm"]$x$, 2, $x$The fistula is the patient's lifeline for dialysis. Anything compressing it may cause thrombosis, so no cuffs, needles or tight dressings on that limb, and the bruit and thrill are checked regularly to confirm patency.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (14, $x$The classic presentation of an acute asthma attack includes$x$, $x$["Coarse crackles at both bases with pink frothy sputum","Pleuritic pain with a friction rub","Expiratory wheeze with prolonged expiration and use of accessory muscles","Inspiratory stridor with drooling"]$x$, 2, $x$Bronchoconstriction obstructs airflow mainly on expiration, giving expiratory wheeze and a prolonged expiratory phase. Ominously, a silent chest means airflow has become too poor to generate wheeze and signals life-threatening asthma.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$),
  (15, $x$Which of the following is a late sign of increased intracranial pressure in an adult?$x$, $x$["Nausea","Mild irritability","Headache","Fixed dilated pupil on one side"]$x$, 3, $x$A unilateral fixed dilated pupil indicates third nerve compression from uncal herniation and is a neurosurgical emergency. Headache, nausea and subtle behaviour change come far earlier and are the ones to act upon.$x$, $x$Medical-Surgical Nursing$x$, $x$hard$x$),
  (16, $x$The most important nursing measure to prevent pressure ulcers in an immobile patient is$x$, $x$["Two-hourly repositioning with pressure-redistributing support and skin inspection","Using a rubber ring under the sacrum","Massaging bony prominences vigorously","Restricting fluids to keep the skin dry"]$x$, 0, $x$Relieving pressure at regular intervals is the cornerstone of prevention, together with keeping skin clean and dry and maintaining nutrition and hydration. Vigorous massage over bony points damages fragile tissue, and ring cushions concentrate pressure around the rim.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (17, $x$The Glasgow Coma Scale assesses$x$, $x$["Pupil size, pulse and blood pressure","Eye opening, verbal response and motor response","Orientation, memory and calculation","Cranial nerves one to twelve"]$x$, 1, $x$The GCS scores eye opening out of 4, verbal response out of 5 and best motor response out of 6, giving a range of 3 to 15. A score of 8 or less indicates coma and usually the need to secure the airway.$x$, $x$Medical-Surgical Nursing$x$, $x$easy$x$),
  (18, $x$The immediate management of a patient with a suspected spinal cord injury includes$x$, $x$["Flexing the neck to check for stiffness","Sitting the patient upright to aid breathing","Encouraging the patient to walk to test power","Immobilising the spine and using log-rolling for any movement"]$x$, 3, $x$Until injury is excluded, the spine is kept in neutral alignment and the patient moved only by log-rolling with enough staff. Flexing the neck or mobilising the patient risks converting an incomplete injury into a complete one.$x$, $x$Medical-Surgical Nursing$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 03-obg-child.txt — 20 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 3 — Midwifery & Obstetrical Nursing, Child Health Nursing$x$, $x$Obstetrics & Child Health$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The normal duration of human pregnancy from the first day of the last menstrual period is$x$, $x$["240 days","260 days","280 days","300 days"]$x$, 2, $x$Pregnancy averages 280 days, or 40 weeks, from the first day of the last menstrual period. Naegele's rule estimates the due date by adding nine months and seven days to that date.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (1, $x$Quickening, the first maternal perception of fetal movement, is usually felt by a primigravida at$x$, $x$["8 to 10 weeks","12 to 14 weeks","18 to 20 weeks","28 to 30 weeks"]$x$, 2, $x$A first-time mother usually feels movements at about 18 to 20 weeks, while a multigravida recognises them earlier, at around 16 to 18 weeks, because she knows the sensation.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (2, $x$The most reliable positive sign of pregnancy is$x$, $x$["Quickening","Demonstration of the fetal heart and fetal parts on ultrasound","Morning sickness","Amenorrhoea"]$x$, 1, $x$Positive signs are those attributable only to the fetus: visualisation of the fetus, audible fetal heart sounds and palpable fetal movements by the examiner. Amenorrhoea and nausea are presumptive, being reported by the woman and possible in other conditions.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (3, $x$The normal fetal heart rate at term is$x$, $x$["160 to 200 beats per minute","80 to 100 beats per minute","110 to 160 beats per minute","60 to 90 beats per minute"]$x$, 2, $x$The accepted normal baseline is 110 to 160 beats per minute. A sustained rate below 110 is fetal bradycardia and above 160 is tachycardia, both requiring assessment.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (4, $x$Pre-eclampsia is defined by hypertension after 20 weeks of gestation together with$x$, $x$["Anaemia","Proteinuria or other end-organ dysfunction","Glycosuria","Polyhydramnios"]$x$, 1, $x$Pre-eclampsia is new hypertension after 20 weeks with proteinuria or evidence of organ involvement such as deranged liver enzymes, low platelets, renal impairment or neurological signs. Once convulsions occur it becomes eclampsia.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (5, $x$The drug of choice for preventing and controlling convulsions in eclampsia is$x$, $x$["Magnesium sulphate","Phenytoin","Nifedipine","Diazepam"]$x$, 0, $x$Magnesium sulphate is superior to diazepam and phenytoin for both prevention and control of eclamptic fits. Toxicity is monitored by checking the knee jerk, respiratory rate and urine output, and calcium gluconate is the antidote.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (6, $x$The most common cause of primary postpartum haemorrhage is$x$, $x$["Uterine atony","Genital tract trauma","Retained placenta","Coagulation disorder"]$x$, 0, $x$Atony, the failure of the uterus to contract after delivery, accounts for the majority of cases. This is why the initial response is to rub up a contraction, empty the bladder and give a uterotonic drug.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (7, $x$The three stages of labour in correct order are$x$, $x$["Dilatation, expulsion of the fetus, expulsion of the placenta","Dilatation, expulsion of the placenta, expulsion of the fetus","Expulsion of the fetus, dilatation, expulsion of the placenta","Effacement, dilatation, expulsion of the placenta"]$x$, 0, $x$The first stage runs from the onset of true labour to full cervical dilatation, the second from full dilatation to delivery of the baby, and the third covers separation and expulsion of the placenta. Some texts add a fourth stage of one to two hours of close observation afterwards.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (8, $x$The most common fetal presentation at term is$x$, $x$["Vertex","Breech","Face","Shoulder"]$x$, 0, $x$About 95 per cent of term fetuses present by the vertex, the most favourable presentation for vaginal delivery because the smallest diameter of the head leads.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (9, $x$In the active management of the third stage of labour, the uterotonic drug is given$x$, $x$["Only after the placenta is delivered","Before delivery of the baby","Within one minute of delivery of the baby","Two hours after delivery"]$x$, 2, $x$Active management involves giving a uterotonic, usually oxytocin, within one minute of the birth, followed by controlled cord traction with counter-traction and uterine massage. It substantially reduces the risk of postpartum haemorrhage.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (10, $x$Colostrum differs from mature breast milk in that it is$x$, $x$["Lower in protein and antibodies","Identical in composition","Higher in protein and immunoglobulins, especially secretory IgA","Higher in fat and lactose"]$x$, 2, $x$Colostrum, secreted in the first few days, is rich in protein, vitamin A and secretory IgA and is lower in fat and lactose. Its immunological value is why it should never be discarded.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (11, $x$Exclusive breastfeeding is recommended for the first$x$, $x$["3 months","6 months","9 months","12 months"]$x$, 1, $x$WHO recommends exclusive breastfeeding for six months, with nothing else including water, followed by appropriate complementary feeding with continued breastfeeding up to two years and beyond.$x$, $x$Obstetrics & Child Health$x$, $x$easy$x$),
  (12, $x$An infant normally doubles the birth weight by about$x$, $x$["3 months","5 to 6 months","9 months","12 months"]$x$, 1, $x$Birth weight roughly doubles by five to six months, triples by one year and quadruples by two years. Failure to follow this pattern is an early clue to faltering growth.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (13, $x$The anterior fontanelle normally closes by$x$, $x$["6 months","12 to 18 months","3 years","9 months"]$x$, 1, $x$The anterior fontanelle closes between 12 and 18 months and the posterior by about 6 to 8 weeks. Delayed closure suggests rickets, hypothyroidism or hydrocephalus, while early closure raises the possibility of craniosynostosis.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (14, $x$According to the national immunisation schedule in India, BCG, OPV-0 and hepatitis B birth dose are given$x$, $x$["At birth","At 10 weeks","At 9 months","At 6 weeks"]$x$, 0, $x$BCG, the zero dose of oral polio vaccine and the birth dose of hepatitis B vaccine are given as soon as possible after birth, ideally within 24 hours for hepatitis B. The primary series of pentavalent and OPV follows at 6, 10 and 14 weeks.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (15, $x$The measles-containing vaccine is first given at$x$, $x$["6 weeks","5 years","Birth","9 to 12 months"]$x$, 3, $x$The first dose of measles-rubella vaccine is given at 9 to 12 months, once maternal antibody has waned enough for the vaccine to take, with a second dose at 16 to 24 months.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (16, $x$A child with severe dehydration from acute diarrhoea should first receive$x$, $x$["Oral rehydration solution only","Antidiarrhoeal drugs","Intravenous fluid such as Ringer lactate","Antibiotics"]$x$, 2, $x$Severe dehydration is plan C and requires immediate intravenous rehydration, usually with Ringer lactate. Oral rehydration is used for some and mild dehydration, and antidiarrhoeal drugs are contraindicated in children.$x$, $x$Obstetrics & Child Health$x$, $x$medium$x$),
  (17, $x$The most useful single sign for assessing pneumonia in a child under five in a community setting is$x$, $x$["Fast breathing for age with chest indrawing","Runny nose","Loss of appetite","Fever"]$x$, 0, $x$The IMNCI approach classifies pneumonia by counting the respiratory rate over one full minute against age-specific cut-offs, and looking for lower chest wall indrawing which indicates severe disease. Fever is too non-specific to guide treatment.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (18, $x$A newborn is assessed at one minute with a heart rate of 130, good crying, active movement, some flexion and a pink body with blue extremities. The Apgar score is$x$, $x$["6","7","8","10"]$x$, 2, $x$Heart rate above 100 scores 2, good crying scores 2 for respiration, active movement scores 2, some flexion scores 1 for muscle tone, and acrocyanosis with a pink body scores 1 for colour, totalling 8. Peripheral blueness alone in the first minutes is common and not alarming.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$),
  (19, $x$Physiological jaundice of the newborn characteristically$x$, $x$["Requires exchange transfusion in every case","Is always associated with pale stools and dark urine","Appears after 24 hours, peaks around days 3 to 5, and resolves within a week or two","Appears within the first 24 hours of life"]$x$, 2, $x$Jaundice appearing in the first 24 hours is always pathological and demands urgent investigation for haemolysis or sepsis. Physiological jaundice appears after the first day, peaks on days three to five in a term baby, and settles without treatment or with phototherapy.$x$, $x$Obstetrics & Child Health$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 04-community-mental.txt — 22 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 4 — Community Health Nursing, Mental Health Nursing$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The infant mortality rate is expressed as the number of deaths under one year of age per$x$, $x$["1000 live births","1000 mid-year population","10000 population","100 live births"]$x$, 0, $x$IMR is deaths of infants under one year per 1000 live births in a given year. It is one of the most sensitive indicators of the overall health and socioeconomic development of a population.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (1, $x$The maternal mortality ratio is expressed per$x$, $x$["1000 population","10000 women","1000 live births","100000 live births"]$x$, 3, $x$Because maternal deaths are relatively rare events, the ratio is expressed per 100,000 live births. It counts deaths during pregnancy or within 42 days of termination of pregnancy from causes related to the pregnancy.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (2, $x$Primary prevention of disease refers to$x$, $x$["Screening of an apparently healthy population","Early diagnosis and prompt treatment","Rehabilitation after disability","Action taken before the disease occurs, such as immunisation and health education"]$x$, 3, $x$Primary prevention acts before disease begins, through health promotion and specific protection such as immunisation. Secondary prevention is early detection and treatment, including screening, and tertiary prevention limits disability and rehabilitates.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (3, $x$Herd immunity refers to$x$, $x$["Immunity acquired after natural infection only","Passive immunity from mother to fetus","Immunity of an individual after vaccination","The protection of a whole community when a sufficient proportion is immune"]$x$, 3, $x$When enough of a population is immune, transmission chains break and even the unimmunised are indirectly protected. The proportion needed rises with how infectious the organism is, which is why measles requires very high coverage.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (4, $x$The cold chain for vaccines requires storage at$x$, $x$["Plus 15 to plus 20 degrees Celsius","Minus 20 degrees Celsius for all vaccines","Room temperature","Plus 2 to plus 8 degrees Celsius at the peripheral level"]$x$, 3, $x$At the health centre level vaccines are held at plus 2 to plus 8 degrees Celsius in an ice-lined refrigerator. Polio vaccine may be kept frozen at higher levels of the chain, whereas freezing destroys the potency of DPT, hepatitis B and tetanus toxoid.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (5, $x$In the epidemiological triad, the three components are$x$, $x$["Agent, host and environment","Time, place and person","Bacteria, virus and fungus","Patient, nurse and doctor"]$x$, 0, $x$Disease results from interaction between agent, host and environment. Time, place and person are the three axes of descriptive epidemiology, which is a different framework.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (6, $x$A disease constantly present in a community at a low or moderate level is described as$x$, $x$["Sporadic","Pandemic","Endemic","Epidemic"]$x$, 2, $x$Endemic means habitually present in an area. An epidemic is a clear excess over expected numbers, a pandemic is an epidemic crossing countries and continents, and sporadic cases are scattered and irregular.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (7, $x$The most appropriate method of disposal of used needles and sharps is$x$, $x$["Yellow bag","Black bag with general waste","Puncture-proof translucent white container","Red bag"]$x$, 2, $x$Under the biomedical waste rules, sharps go into puncture-proof, leak-proof white translucent containers. Yellow is for anatomical and soiled waste requiring incineration and red for contaminated recyclable plastics such as tubing.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (8, $x$In the ASHA scheme, the ASHA worker functions primarily as$x$, $x$["A medical officer","A laboratory technician","A qualified staff nurse in a hospital","A community health volunteer and link between the community and the health system"]$x$, 3, $x$The Accredited Social Health Activist is a trained female volunteer resident in the village who mobilises the community, promotes institutional delivery and immunisation, and links families with health services. She is paid by performance-based incentives.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (9, $x$Chlorination of drinking water at the household level is most effective when the free residual chlorine after 30 minutes of contact is$x$, $x$["0.1 mg per litre","0.5 mg per litre","5 mg per litre","10 mg per litre"]$x$, 1, $x$A free residual chlorine of about 0.5 mg per litre after 30 minutes contact indicates that the demand has been met and the water is safe. Very high residuals make the water unpalatable and are unnecessary.$x$, $x$Community Health Nursing$x$, $x$hard$x$),
  (10, $x$Directly Observed Treatment, Short course, in the tuberculosis programme means$x$, $x$["Only sputum-positive patients are treated","The patient collects a month of tablets at a time","Treatment is given only in hospital","Treatment is swallowed in the presence of an observer who records it"]$x$, 3, $x$DOTS requires that doses be swallowed under observation and recorded, which secures adherence and prevents the emergence of drug resistance. It is combined with quality-assured diagnosis, an assured drug supply and systematic monitoring.$x$, $x$Community Health Nursing$x$, $x$medium$x$),
  (11, $x$The vector responsible for transmitting malaria is$x$, $x$["Sandfly","Aedes aegypti","Female Anopheles mosquito","Culex mosquito"]$x$, 2, $x$The female Anopheles transmits malaria. Culex transmits filariasis and Japanese encephalitis, Aedes aegypti transmits dengue, chikungunya and yellow fever, and the sandfly transmits kala-azar.$x$, $x$Community Health Nursing$x$, $x$easy$x$),
  (12, $x$The defence mechanism in which an unacceptable impulse is transferred to a less threatening target is$x$, $x$["Sublimation","Regression","Displacement","Projection"]$x$, 2, $x$Displacement redirects feeling onto a safer object, as when anger at a superior is taken out at home. Projection attributes one's own feelings to someone else, regression retreats to earlier behaviour, and sublimation channels the impulse into something socially valued.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (13, $x$A fixed false belief that is not amenable to reason and is out of keeping with the person's culture is$x$, $x$["Hallucination","Obsession","Delusion","Illusion"]$x$, 2, $x$A delusion is a disorder of thought content. A hallucination is a perception without any external stimulus, an illusion is a misinterpretation of a real stimulus, and an obsession is a recurrent intrusive thought the person recognises as their own and resists.$x$, $x$Mental Health Nursing$x$, $x$easy$x$),
  (14, $x$The most common type of hallucination in schizophrenia is$x$, $x$["Visual","Tactile","Auditory","Olfactory"]$x$, 2, $x$Auditory hallucinations, often voices commenting on or discussing the patient, are the commonest. Prominent visual hallucinations should raise suspicion of an organic cause such as delirium or substance withdrawal.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (15, $x$A patient on lithium therapy should be closely monitored for$x$, $x$["Serum amylase","Liver enzymes only","Blood glucose only","Serum lithium level, renal and thyroid function"]$x$, 3, $x$Lithium has a narrow therapeutic index of roughly 0.6 to 1.2 mEq per litre, is excreted by the kidney and can cause hypothyroidism, so levels, renal function and thyroid function are all monitored. Early toxicity shows as coarse tremor, vomiting, diarrhoea, ataxia and drowsiness.$x$, $x$Mental Health Nursing$x$, $x$hard$x$),
  (16, $x$Which of the following is a negative symptom of schizophrenia?$x$, $x$["Delusion","Disorganised speech","Hallucination","Affective flattening and avolition"]$x$, 3, $x$Negative symptoms are the absence of normal function: blunted affect, poverty of speech, loss of volition and social withdrawal. Delusions, hallucinations and disorganised speech are positive symptoms, being additions to normal experience.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (17, $x$The most important nursing priority for a patient who has expressed suicidal intent is$x$, $x$["Leaving the patient alone to rest","Encouraging the patient to join group activities","Discussing the topic only if the patient raises it","Ensuring continuous observation and a safe environment free of harmful objects"]$x$, 3, $x$Safety comes first, through close observation and removal of means. Asking directly about suicidal thoughts does not plant the idea, and avoiding the subject leaves risk unassessed.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (18, $x$Extrapyramidal side effects of typical antipsychotic drugs include$x$, $x$["Dystonia, akathisia, parkinsonism and tardive dyskinesia","Polyuria and polydipsia","Hypertension and tachycardia only","Photosensitivity only"]$x$, 0, $x$Blockade of dopamine in the nigrostriatal pathway produces acute dystonia, restless akathisia, drug-induced parkinsonism and, after prolonged use, tardive dyskinesia. Neuroleptic malignant syndrome, with rigidity, fever and autonomic instability, is the rare and life-threatening extreme.$x$, $x$Mental Health Nursing$x$, $x$hard$x$),
  (19, $x$Electroconvulsive therapy is most clearly indicated in$x$, $x$["Severe depression with high suicidal risk or refusal of food","Personality disorder","Simple phobia","Mild anxiety disorder"]$x$, 0, $x$ECT works quickly and is used when the situation is urgent, such as severe depression with strong suicidal intent, refusal to eat or drink, catatonia, or when drugs have failed. It has no place in mild anxiety or personality disorder.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (20, $x$In the therapeutic nurse-patient relationship, the working phase is characterised by$x$, $x$["Collecting demographic data","Establishing trust and setting boundaries","Exploring problems and developing coping strategies","Summarising progress and preparing for separation"]$x$, 2, $x$The relationship moves through orientation, where trust and contract are established, the working phase where issues are explored and new behaviours tried, and termination where gains are consolidated and separation is worked through.$x$, $x$Mental Health Nursing$x$, $x$medium$x$),
  (21, $x$Delirium is distinguished from dementia chiefly by$x$, $x$["Acute onset, fluctuating course and clouding of consciousness","Absence of any treatable cause","Gradual onset over months and clear consciousness","Permanent irreversible course"]$x$, 0, $x$Delirium comes on over hours to days, fluctuates, impairs attention and consciousness and usually has a reversible physical cause such as infection, hypoxia or drugs. Dementia begins insidiously, progresses over months to years and leaves consciousness clear until very late.$x$, $x$Mental Health Nursing$x$, $x$hard$x$)
) as v(pos, question, options, ci, exp, topic, diff);

-- 05-pharma-micro-research.txt — 18 questions
with b as (
  insert into tests (title, topic, difficulty, duration_minutes)
  values ($x$Batch 5 — Pharmacology, Microbiology & Pathology, Nursing Research & Statistics, Management$x$, $x$Mixed$x$, 'medium', 60)
  returning id
)
insert into questions (test_id, position, question, options, correct_index, explanation, topic, difficulty)
select b.id, v.pos::int, v.question, v.options::jsonb, v.ci::int, v.exp, v.topic, v.diff
from b, (values
  (0, $x$The antidote for warfarin overdose is$x$, $x$["Vitamin K","Flumazenil","Protamine sulphate","Atropine"]$x$, 0, $x$Warfarin blocks vitamin K dependent clotting factors II, VII, IX and X, so vitamin K reverses it, with prothrombin complex concentrate or fresh frozen plasma added when bleeding is severe. Protamine reverses heparin.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (1, $x$The antidote for paracetamol poisoning is$x$, $x$["Atropine","Naloxone","Deferoxamine","N-acetylcysteine"]$x$, 3, $x$N-acetylcysteine replenishes glutathione, which detoxifies the reactive metabolite responsible for hepatic necrosis. It is most effective when started within eight hours of ingestion, so treatment is not delayed for levels when the history suggests serious overdose.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (2, $x$Which route of drug administration gives the most rapid onset of action?$x$, $x$["Oral","Subcutaneous","Intramuscular","Intravenous"]$x$, 3, $x$The intravenous route delivers the drug straight into the circulation with 100 per cent bioavailability and no absorption phase. It is also the least forgiving, because once given the dose cannot be retrieved.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (3, $x$The five rights of medication administration are the right patient, right drug, right dose, right route and$x$, $x$["Right time","Right diagnosis","Right nurse","Right prescription"]$x$, 0, $x$The classic five rights are patient, drug, dose, route and time. Many services now add right documentation, right reason and the patient's right to refuse.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (4, $x$Aminoglycoside antibiotics such as gentamicin are chiefly toxic to the$x$, $x$["Liver and pancreas","Bone marrow","Kidney and eighth cranial nerve","Skin"]$x$, 2, $x$Nephrotoxicity and ototoxicity, affecting both hearing and balance, are the characteristic dangers, so renal function and levels are monitored and the patient is asked about tinnitus, hearing loss and unsteadiness.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (5, $x$A patient receiving intravenous potassium chloride must never be given it$x$, $x$["Undiluted as a rapid intravenous push","Diluted in intravenous fluid","With cardiac monitoring","Through an infusion pump"]$x$, 0, $x$Concentrated potassium given as a bolus causes fatal cardiac arrest. It must always be diluted, given slowly by controlled infusion, and the site watched, since potassium is intensely irritant to veins.$x$, $x$Nursing Foundations$x$, $x$hard$x$),
  (6, $x$Which drug group requires the nurse to teach the patient to rise slowly from lying or sitting?$x$, $x$["Antihypertensives","Antacids","Bulk laxatives","Topical antifungals"]$x$, 0, $x$Antihypertensives, and particularly alpha blockers and vasodilators, cause postural hypotension. Teaching the patient to change position slowly and to dangle the legs before standing prevents dizziness and falls.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (7, $x$Insulin should ideally be stored$x$, $x$["In the refrigerator at 2 to 8 degrees Celsius, with the vial in use kept at room temperature","In the freezer","In direct sunlight","At 37 degrees Celsius"]$x$, 0, $x$Unopened insulin keeps in the refrigerator until its expiry date, while the vial or pen in use may stay at room temperature for about four weeks and is more comfortable to inject. Freezing destroys insulin and it must then be discarded.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (8, $x$Tuberculosis is caused by an organism best described as$x$, $x$["A Gram-negative coccus","A spirochaete","An acid-fast bacillus","A fungus"]$x$, 2, $x$Mycobacterium tuberculosis has a waxy mycolic acid cell wall that resists decolourisation by acid alcohol, so it is demonstrated by the Ziehl-Neelsen stain. That same wall makes it slow growing and hard to treat.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (9, $x$The most common mode of transmission of hepatitis A is$x$, $x$["Blood transfusion","Perinatal","Sexual contact","Faeco-oral"]$x$, 3, $x$Hepatitis A and E spread by the faeco-oral route through contaminated food and water and do not become chronic. Hepatitis B, C and D spread by blood, sexual contact and perinatally, and B and C may become chronic.$x$, $x$Basic Sciences$x$, $x$easy$x$),
  (10, $x$Standard precautions are applied to$x$, $x$["Only during surgical procedures","Only patients in isolation rooms","Only patients known to have an infection","All patients regardless of their diagnosis or infection status"]$x$, 3, $x$Standard precautions assume that the blood and body fluids of every patient may be infectious, and are used for all patients at all times. Transmission-based precautions of contact, droplet or airborne type are added when a specific risk is known.$x$, $x$Basic Sciences$x$, $x$medium$x$),
  (11, $x$The window period in HIV infection refers to the interval between$x$, $x$["Two consecutive negative tests","Exposure and the appearance of detectable antibodies","Diagnosis and the start of treatment","Infection and death"]$x$, 1, $x$During the window period the person is infected and infectious but the antibody test may still be negative, which is why donated blood is screened by more sensitive methods and why repeat testing is advised after a risk exposure.$x$, $x$Basic Sciences$x$, $x$hard$x$),
  (12, $x$In a normal distribution, approximately what percentage of observations lies within one standard deviation of the mean?$x$, $x$["50 per cent","68 per cent","95 per cent","99 per cent"]$x$, 1, $x$About 68 per cent of values lie within one standard deviation, 95 per cent within two and 99.7 per cent within three. This is the basis for interpreting reference ranges and confidence intervals.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (13, $x$A sampling method in which every member of the population has an equal and independent chance of being selected is$x$, $x$["Purposive sampling","Simple random sampling","Quota sampling","Convenience sampling"]$x$, 1, $x$Simple random sampling gives every unit an equal chance and allows the findings to be generalised. Convenience, purposive and quota sampling are non-probability methods, which are quicker but carry a higher risk of bias.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (14, $x$The measure of central tendency least affected by extreme values is the$x$, $x$["Median","Mean","Standard deviation","Range"]$x$, 0, $x$The median is the middle value once data are ordered, so a few very large or very small observations barely move it. This is why income and length of stay, which are skewed, are usually reported as medians.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (15, $x$In research ethics, obtaining informed consent requires that the participant$x$, $x$["Signs the form without explanation to save time","Understands the purpose, risks and benefits, and may withdraw at any time without penalty","Consents on behalf of the whole ward","Is told only the benefits"]$x$, 1, $x$Informed consent rests on disclosure, comprehension and voluntariness, including the freedom to refuse or withdraw without any effect on care. Concealing risks or applying pressure invalidates the consent.$x$, $x$Nursing Foundations$x$, $x$easy$x$),
  (16, $x$A null hypothesis states that$x$, $x$["The study is ethically approved","The sample is representative","There is no difference or no association between the variables","There is a significant difference between the groups"]$x$, 2, $x$The null hypothesis asserts no difference or no relationship, and statistical testing asks whether the data give enough evidence to reject it. A p value below 0.05 is the conventional threshold for doing so.$x$, $x$Nursing Foundations$x$, $x$medium$x$),
  (17, $x$Delegation by a nurse in charge is appropriate when$x$, $x$["The task is within the scope of practice of the person delegated to, who is competent and supervised","The nurse in charge is simply too busy","No handover or follow-up is needed afterwards","The task requires nursing judgement that only the registered nurse can make"]$x$, 0, $x$Delegation requires the right task, the right circumstance, the right person, the right communication and the right supervision. Accountability for the outcome remains with the delegating nurse, so assessment and judgement are never delegated.$x$, $x$Nursing Foundations$x$, $x$medium$x$)
) as v(pos, question, options, ci, exp, topic, diff);

commit;

-- Expect: 104 rows inserted across 5 batches.
-- Check with:  select topic, difficulty, count(*) from questions group by 1,2 order by 1,2;
